/* HWIF_DEC_PIC_INF                 */ {/*swreg*/  1,  1, 24,  1},
/* HWIF_DEC_TILE_INT                */ {/*swreg*/  1,  1, 23,  1},
/* HWIF_DEC_LINE_CNT_INT            */ {/*swreg*/  1,  1, 22,  1},
/* HWIF_DEC_EXT_TIMEOUT_INT         */ {/*swreg*/  1,  1, 21,  1},
/* HWIF_DEC_NO_SLICE_INT            */ {/*swreg*/  1,  1, 20,  1},
/* HWIF_DEC_LAST_SLICE_INT          */ {/*swreg*/  1,  1, 19,  1},
/* HWIF_DEC_TIMEOUT                 */ {/*swreg*/  1,  1, 18,  1},
/* HWIF_DEC_SLICE_INT               */ {/*swreg*/  1,  1, 17,  1},
/* HWIF_DEC_ERROR_INT               */ {/*swreg*/  1,  1, 16,  1},
/* HWIF_DEC_ASO_INT                 */ {/*swreg*/  1,  1, 15,  1},
/* HWIF_DEC_BUFFER_INT              */ {/*swreg*/  1,  1, 14,  1},
/* HWIF_DEC_BUS_INT                 */ {/*swreg*/  1,  1, 13,  1},
/* HWIF_DEC_RDY_INT                 */ {/*swreg*/  1,  1, 12,  1},
/* HWIF_DEC_ABORT_INT               */ {/*swreg*/  1,  1, 11,  1},
/* HWIF_DEC_IRQ                     */ {/*swreg*/  1,  1,  8,  1},
/* HWIF_DEC_TILE_INT_E              */ {/*swreg*/  1,  1,  7,  1},
/* HWIF_DEC_SELF_RESET_DIS          */ {/*swreg*/  1,  1,  6,  1},
/* HWIF_DEC_ABORT_E                 */ {/*swreg*/  1,  1,  5,  1},
/* HWIF_DEC_IRQ_DIS                 */ {/*swreg*/  1,  1,  4,  1},
/* HWIF_DEC_TIMEOUT_SOURCE          */ {/*swreg*/  1,  1,  3,  1},
/* HWIF_DEC_BUS_INT_DIS             */ {/*swreg*/  1,  1,  2,  1},
/* HWIF_DEC_STRM_CORRUPTED          */ {/*swreg*/  1,  1,  1,  0},
/* HWIF_DEC_E                       */ {/*swreg*/  1,  1,  0,  1},
/* HWIF_DEC_STRM_SWAP               */ {/*swreg*/  2,  4, 28,  1},
/* HWIF_DEC_PIC_SWAP                */ {/*swreg*/  2,  4, 24,  1},
/* HWIF_DEC_DIRMV_SWAP              */ {/*swreg*/  2,  4, 20,  1},
/* HWIF_TILED_MODE_MSB              */ {/*swreg*/  2,  1, 17,  1},
/* HWIF_DEC_TAB_SWAP                */ {/*swreg*/  2,  4, 12,  1},
/* HWIF_DEC_CLK_GATE_E              */ {/*swreg*/  2,  1, 10,  1},
/* HWIF_TILED_MODE_LSB              */ {/*swreg*/  2,  1,  7,  1},
/* HWIF_DEC_MODE                    */ {/*swreg*/  3,  5, 27,  1},
/* HWIF_SKIP_MODE                   */ {/*swreg*/  3,  1, 26,  1},
/* HWIF_DIVX3_E                     */ {/*swreg*/  3,  1, 25,  1},
/* HWIF_RLC_MODE_E                  */ {/*swreg*/  3,  1, 24,  1},
/* HWIF_PIC_INTERLACE_E             */ {/*swreg*/  3,  1, 23,  1},
/* HWIF_PIC_FIELDMODE_E             */ {/*swreg*/  3,  1, 22,  1},
/* HWIF_PIC_B_E                     */ {/*swreg*/  3,  1, 21,  1},
/* HWIF_PIC_INTER_E                 */ {/*swreg*/  3,  1, 20,  1},
/* HWIF_PIC_TOPFIELD_E              */ {/*swreg*/  3,  1, 19,  1},
/* HWIF_FWD_INTERLACE_E             */ {/*swreg*/  3,  1, 18,  1},
/* HWIF_SORENSON_E                  */ {/*swreg*/  3,  1, 17,  1},
/* HWIF_REF_TOPFIELD_E              */ {/*swreg*/  3,  1, 16,  1},
/* HWIF_DEC_OUT_DIS                 */ {/*swreg*/  3,  1, 15,  1},
/* HWIF_FILTERING_DIS               */ {/*swreg*/  3,  1, 14,  1},
/* HWIF_WEBP_E                      */ {/*swreg*/  3,  1, 13,  1},
/* HWIF_MVC_E                       */ {/*swreg*/  3,  1, 13,  1},
/* HWIF_PIC_FIXED_QUANT             */ {/*swreg*/  3,  1, 13,  1},
/* HWIF_WRITE_MVS_E                 */ {/*swreg*/  3,  1, 12,  1},
/* HWIF_REFTOPFIRST_E               */ {/*swreg*/  3,  1, 11,  1},
/* HWIF_SEQ_MBAFF_E                 */ {/*swreg*/  3,  1, 10,  1},
/* HWIF_PICORD_COUNT_E              */ {/*swreg*/  3,  1,  9,  1},
/* HWIF_DEC_OUT_EC_BYPASS           */ {/*swreg*/  3,  1,  8,  1},
/* HWIF_APF_ONE_PID                 */ {/*swreg*/  3,  1,  7,  1},
/* HWIF_L2_SHAPER_E                 */ {/*swreg*/  3,  1,  3,  1},
/* HWIF_BUFFER_EMPTY_INT_E          */ {/*swreg*/  3,  1,  2,  1},
/* HWIF_BLOCK_BUFFER_MODE_E         */ {/*swreg*/  3,  1,  1,  1},
/* HWIF_LAST_BUFFER_E               */ {/*swreg*/  3,  1,  0,  1},
/* HWIF_PIC_MB_WIDTH                */ {/*swreg*/  4,  9, 23,  1},
/* HWIF_MB_WIDTH_OFF                */ {/*swreg*/  4,  4, 19,  1},
/* HWIF_PIC_MB_HEIGHT_P             */ {/*swreg*/  4,  8, 11,  1},
/* HWIF_MB_HEIGHT_OFF               */ {/*swreg*/  4,  4,  7,  1},
/* HWIF_PIC_WIDTH_IN_CBS            */ {/*swreg*/  4, 13, 19,  1},
/* HWIF_PIC_HEIGHT_IN_CBS           */ {/*swreg*/  4, 13,  6,  1},
/* HWIF_ALT_SCAN_E                  */ {/*swreg*/  4,  1,  6,  1},
/* HWIF_TOPFIELDFIRST_E             */ {/*swreg*/  4,  1,  5,  1},
/* HWIF_REF_FRAMES                  */ {/*swreg*/  4,  5,  0,  1},
/* HWIF_PIC_MB_W_EXT                */ {/*swreg*/  4,  3,  3,  1},
/* HWIF_PIC_MB_H_EXT                */ {/*swreg*/  4,  3,  0,  1},
/* HWIF_PIC_REFER_FLAG              */ {/*swreg*/  4,  1,  0,  1},
/* HWIF_STRM_START_BIT              */ {/*swreg*/  5,  7, 25,  1},
/* HWIF_SCALING_LIST_E              */ {/*swreg*/  5,  1, 24,  1},
/* HWIF_TYPE1_QUANT_E               */ {/*swreg*/  5,  1, 24,  1},
/* HWIF_CH_QP_OFFSET                */ {/*swreg*/  5,  5, 19,  1},
/* HWIF_CH_QP_OFFSET2               */ {/*swreg*/  5,  5, 14,  1},
/* HWIF_SIGN_DATA_HIDE              */ {/*swreg*/  5,  1, 12,  1},
/* HWIF_TEMPOR_MVP_E                */ {/*swreg*/  5,  1, 11,  1},
/* HWIF_MAX_CU_QPD_DEPTH            */ {/*swreg*/  5,  6,  5,  1},
/* HWIF_CU_QPD_E                    */ {/*swreg*/  5,  1,  4,  1},
/* HWIF_FIELDPIC_FLAG_E             */ {/*swreg*/  5,  1,  0,  1},
/* HWIF_INTRADC_VLC_THR             */ {/*swreg*/  5,  3, 16,  1},
/* HWIF_VOP_TIME_INCR               */ {/*swreg*/  5, 16,  0,  1},
/* HWIF_DQ_PROFILE                  */ {/*swreg*/  5,  1, 24,  1},
/* HWIF_DQBI_LEVEL                  */ {/*swreg*/  5,  1, 23,  1},
/* HWIF_RANGE_RED_FRM_E             */ {/*swreg*/  5,  1, 22,  1},
/* HWIF_FAST_UVMC_E                 */ {/*swreg*/  5,  1, 20,  1},
/* HWIF_TRANSDCTAB                  */ {/*swreg*/  5,  1, 17,  1},
/* HWIF_TRANSACFRM                  */ {/*swreg*/  5,  2, 15,  1},
/* HWIF_TRANSACFRM2                 */ {/*swreg*/  5,  2, 13,  1},
/* HWIF_MB_MODE_TAB                 */ {/*swreg*/  5,  3, 10,  1},
/* HWIF_MVTAB                       */ {/*swreg*/  5,  3,  7,  1},
/* HWIF_CBPTAB                      */ {/*swreg*/  5,  3,  4,  1},
/* HWIF_2MV_BLK_PAT_TAB             */ {/*swreg*/  5,  2,  2,  1},
/* HWIF_4MV_BLK_PAT_TAB             */ {/*swreg*/  5,  2,  0,  1},
/* HWIF_QSCALE_TYPE                 */ {/*swreg*/  5,  1, 24,  1},
/* HWIF_CON_MV_E                    */ {/*swreg*/  5,  1,  4,  1},
/* HWIF_INTRA_DC_PREC               */ {/*swreg*/  5,  2,  2,  1},
/* HWIF_INTRA_VLC_TAB               */ {/*swreg*/  5,  1,  1,  1},
/* HWIF_FRAME_PRED_DCT              */ {/*swreg*/  5,  1,  0,  1},
/* HWIF_JPEG_QTABLES                */ {/*swreg*/  5,  2, 11,  1},
/* HWIF_JPEG_MODE                   */ {/*swreg*/  5,  3,  8,  1},
/* HWIF_JPEG_FILRIGHT_E             */ {/*swreg*/  5,  1,  7,  1},
/* HWIF_JPEG_STREAM_ALL             */ {/*swreg*/  5,  1,  6,  1},
/* HWIF_CR_AC_VLCTABLE              */ {/*swreg*/  5,  1,  5,  1},
/* HWIF_CB_AC_VLCTABLE              */ {/*swreg*/  5,  1,  4,  1},
/* HWIF_CR_DC_VLCTABLE              */ {/*swreg*/  5,  1,  3,  1},
/* HWIF_CB_DC_VLCTABLE              */ {/*swreg*/  5,  1,  2,  1},
/* HWIF_CR_DC_VLCTABLE3             */ {/*swreg*/  5,  1,  1,  1},
/* HWIF_CB_DC_VLCTABLE3             */ {/*swreg*/  5,  1,  0,  1},
/* HWIF_STRM1_START_BIT             */ {/*swreg*/  5,  6, 18,  1},
/* HWIF_HUFFMAN_E                   */ {/*swreg*/  5,  1, 17,  1},
/* HWIF_MULTISTREAM_E               */ {/*swreg*/  5,  1, 16,  1},
/* HWIF_BOOLEAN_VALUE               */ {/*swreg*/  5,  8,  8,  1},
/* HWIF_BOOLEAN_RANGE               */ {/*swreg*/  5,  8,  0,  1},
/* HWIF_ALPHA_OFFSET                */ {/*swreg*/  5,  5,  5,  1},
/* HWIF_BETA_OFFSET                 */ {/*swreg*/  5,  5,  0,  1},
/* HWIF_STREAM_LEN                  */ {/*swreg*/  6, 32,  0,  1},
/* HWIF_CABAC_E                     */ {/*swreg*/  7,  1, 31,  1},
/* HWIF_CABAC_INIT_PRESENT          */ {/*swreg*/  7,  1, 31,  1},
/* HWIF_BLACKWHITE_E                */ {/*swreg*/  7,  1, 30,  1},
/* HWIF_DIR_8X8_INFER_E             */ {/*swreg*/  7,  1, 29,  1},
/* HWIF_WEIGHT_PRED_E               */ {/*swreg*/  7,  1, 28,  1},
/* HWIF_WEIGHT_BIPR_IDC             */ {/*swreg*/  7,  2, 26,  1},
/* HWIF_AVS_H264_H_EXT              */ {/*swreg*/  7,  1, 25,  1},
/* HWIF_CH_8PIX_ILEAV_E             */ {/*swreg*/  7,  1, 24,  1},
/* HWIF_FRAMENUM_LEN                */ {/*swreg*/  7,  5, 16,  1},
/* HWIF_FRAMENUM                    */ {/*swreg*/  7, 16,  0,  1},
/* HWIF_BITPLANE0_E                 */ {/*swreg*/  7,  1, 31,  1},
/* HWIF_BITPLANE1_E                 */ {/*swreg*/  7,  1, 30,  1},
/* HWIF_BITPLANE2_E                 */ {/*swreg*/  7,  1, 29,  1},
/* HWIF_ALT_PQUANT                  */ {/*swreg*/  7,  5, 24,  1},
/* HWIF_DQ_EDGES                    */ {/*swreg*/  7,  4, 20,  1},
/* HWIF_TTMBF                       */ {/*swreg*/  7,  1, 19,  1},
/* HWIF_PQINDEX                     */ {/*swreg*/  7,  5, 14,  1},
/* HWIF_VC1_HEIGHT_EXT              */ {/*swreg*/  7,  1, 13,  1},
/* HWIF_BILIN_MC_E                  */ {/*swreg*/  7,  1, 12,  1},
/* HWIF_UNIQP_E                     */ {/*swreg*/  7,  1, 11,  1},
/* HWIF_HALFQP_E                    */ {/*swreg*/  7,  1, 10,  1},
/* HWIF_TTFRM                       */ {/*swreg*/  7,  2,  8,  1},
/* HWIF_2ND_BYTE_EMUL_E             */ {/*swreg*/  7,  1,  7,  1},
/* HWIF_DQUANT_E                    */ {/*swreg*/  7,  1,  6,  1},
/* HWIF_VC1_ADV_E                   */ {/*swreg*/  7,  1,  5,  1},
/* HWIF_PJPEG_FILDOWN_E             */ {/*swreg*/  7,  1, 26,  1},
/* HWIF_PJPEG_WDIV8                 */ {/*swreg*/  7,  1, 25,  1},
/* HWIF_PJPEG_HDIV8                 */ {/*swreg*/  7,  1, 24,  1},
/* HWIF_PJPEG_AH                    */ {/*swreg*/  7,  4, 20,  1},
/* HWIF_PJPEG_AL                    */ {/*swreg*/  7,  4, 16,  1},
/* HWIF_PJPEG_SS                    */ {/*swreg*/  7,  8,  8,  1},
/* HWIF_PJPEG_SE                    */ {/*swreg*/  7,  8,  0,  1},
/* HWIF_DCT1_START_BIT              */ {/*swreg*/  7,  6, 26,  1},
/* HWIF_DCT2_START_BIT              */ {/*swreg*/  7,  6, 20,  1},
/* HWIF_CH_MV_RES                   */ {/*swreg*/  7,  1, 13,  1},
/* HWIF_INIT_DC_MATCH0              */ {/*swreg*/  7,  3,  9,  1},
/* HWIF_INIT_DC_MATCH1              */ {/*swreg*/  7,  3,  6,  1},
/* HWIF_VP7_VERSION                 */ {/*swreg*/  7,  1,  5,  1},
/* HWIF_FILT_SLICE_BORDER           */ {/*swreg*/  7,  1, 25,  1},
/* HWIF_FILT_TILE_BORDER            */ {/*swreg*/  7,  1, 24,  1},
/* HWIF_ASYM_PRED_E                 */ {/*swreg*/  7,  1, 23,  1},
/* HWIF_SAO_E                       */ {/*swreg*/  7,  1, 22,  1},
/* HWIF_PCM_FILT_DISABLE            */ {/*swreg*/  7,  1, 21,  1},
/* HWIF_SLICE_CHQP_FLAG             */ {/*swreg*/  7,  1, 20,  1},
/* HWIF_DEPEND_SLICE_E              */ {/*swreg*/  7,  1, 19,  1},
/* HWIF_FILT_OVERRIDE_E             */ {/*swreg*/  7,  1, 18,  1},
/* HWIF_STRONG_SMOOTH_E             */ {/*swreg*/  7,  1, 17,  1},
/* HWIF_FILT_OFFSET_BETA            */ {/*swreg*/  7,  5, 12,  1},
/* HWIF_FILT_OFFSET_TC              */ {/*swreg*/  7,  5,  7,  1},
/* HWIF_SLICE_HDR_EXT_E             */ {/*swreg*/  7,  1,  6,  1},
/* HWIF_SLICE_HDR_EBITS             */ {/*swreg*/  7,  3,  3,  1},
/* HWIF_CONST_INTRA_E               */ {/*swreg*/  8,  1, 31,  1},
/* HWIF_FILT_CTRL_PRES              */ {/*swreg*/  8,  1, 30,  1},
/* HWIF_RDPIC_CNT_PRES              */ {/*swreg*/  8,  1, 29,  1},
/* HWIF_8X8TRANS_FLAG_E             */ {/*swreg*/  8,  1, 28,  1},
/* HWIF_REFPIC_MK_LEN               */ {/*swreg*/  8, 11, 17,  1},
/* HWIF_IDR_PIC_E                   */ {/*swreg*/  8,  1, 16,  1},
/* HWIF_IDR_PIC_ID                  */ {/*swreg*/  8, 16,  0,  1},
/* HWIF_PCM_BITDEPTH_Y              */ {/*swreg*/  8,  4, 12,  1},
/* HWIF_PCM_BITDEPTH_C              */ {/*swreg*/  8,  4,  8,  1},
/* HWIF_BIT_DEPTH_Y_MINUS8          */ {/*swreg*/  8,  2,  6,  1},
/* HWIF_BIT_DEPTH_C_MINUS8          */ {/*swreg*/  8,  2,  4,  1},
/* HWIF_MV_SCALEFACTOR              */ {/*swreg*/  8,  8, 24,  1},
/* HWIF_REF_DIST_FWD                */ {/*swreg*/  8,  5, 19,  1},
/* HWIF_REF_DIST_BWD                */ {/*swreg*/  8,  5, 14,  1},
/* HWIF_LOOP_FILT_LIMIT             */ {/*swreg*/  8,  4, 14,  1},
/* HWIF_VARIANCE_TEST_E             */ {/*swreg*/  8,  1, 13,  1},
/* HWIF_MV_THRESHOLD                */ {/*swreg*/  8,  3, 10,  1},
/* HWIF_VAR_THRESHOLD               */ {/*swreg*/  8, 10,  0,  1},
/* HWIF_DIVX_IDCT_E                 */ {/*swreg*/  8,  1,  8,  1},
/* HWIF_DIVX3_SLICE_SIZE            */ {/*swreg*/  8,  8,  0,  1},
/* HWIF_PJPEG_REST_FREQ             */ {/*swreg*/  8, 16,  0,  1},
/* HWIF_RV_PROFILE                  */ {/*swreg*/  8,  2, 30,  1},
/* HWIF_RV_OSV_QUANT                */ {/*swreg*/  8,  2, 28,  1},
/* HWIF_RV_FWD_SCALE                */ {/*swreg*/  8, 14, 14,  1},
/* HWIF_RV_BWD_SCALE                */ {/*swreg*/  8, 14,  0,  1},
/* HWIF_INIT_DC_COMP0               */ {/*swreg*/  8, 16, 16,  1},
/* HWIF_INIT_DC_COMP1               */ {/*swreg*/  8, 16,  0,  1},
/* HWIF_PPS_ID                      */ {/*swreg*/  9,  8, 24,  1},
/* HWIF_REFIDX1_ACTIVE              */ {/*swreg*/  9,  5, 19,  1},
/* HWIF_REFIDX0_ACTIVE              */ {/*swreg*/  9,  5, 14,  1},
/* HWIF_HDR_SKIP_LENGTH             */ {/*swreg*/  9, 14,  0,  1},
/* HWIF_POC_LENGTH                  */ {/*swreg*/  9,  8,  0,  1},
/* HWIF_ICOMP0_E                    */ {/*swreg*/  9,  1, 24,  1},
/* HWIF_ISCALE0                     */ {/*swreg*/  9,  8, 16,  1},
/* HWIF_ISHIFT0                     */ {/*swreg*/  9, 16,  0,  1},
/* HWIF_STREAM1_LEN                 */ {/*swreg*/  9, 24,  0,  1},
/* HWIF_PIC_SLICE_AM                */ {/*swreg*/  9, 13,  0,  1},
/* HWIF_COEFFS_PART_AM              */ {/*swreg*/  9,  4, 24,  1},
/* HWIF_PINIT_RLIST_F9              */ {/*swreg*/ 10,  5, 25,  1},
/* HWIF_PINIT_RLIST_F8              */ {/*swreg*/ 10,  5, 20,  1},
/* HWIF_PINIT_RLIST_F7              */ {/*swreg*/ 10,  5, 15,  1},
/* HWIF_PINIT_RLIST_F6              */ {/*swreg*/ 10,  5, 10,  1},
/* HWIF_PINIT_RLIST_F5              */ {/*swreg*/ 10,  5,  5,  1},
/* HWIF_PINIT_RLIST_F4              */ {/*swreg*/ 10,  5,  0,  1},
/* HWIF_ICOMP1_E                    */ {/*swreg*/ 10,  1, 24,  1},
/* HWIF_ISCALE1                     */ {/*swreg*/ 10,  8, 16,  1},
/* HWIF_ISHIFT1                     */ {/*swreg*/ 10, 16,  0,  1},
/* HWIF_INIT_QP_V0                  */ {/*swreg*/ 10,  6, 25,  1},
/* HWIF_NUM_TILE_COLS_V0            */ {/*swreg*/ 10,  5, 20,  1},
/* HWIF_NUM_TILE_COLS               */ {/*swreg*/ 10,  5, 19,  1},
/* HWIF_NUM_TILE_COLS_8K            */ {/*swreg*/ 10,  7, 17,  1},
/* HWIF_NUM_TILE_ROWS_V0            */ {/*swreg*/ 10,  5, 15,  1},
/* HWIF_NUM_TILE_ROWS               */ {/*swreg*/ 10,  5, 14,  1},
/* HWIF_NUM_TILE_ROWS_8K            */ {/*swreg*/ 10,  5, 12,  1},
/* HWIF_TILE_ENABLE                 */ {/*swreg*/ 10,  1,  1,  1},
/* HWIF_ENTR_CODE_SYNCH_E           */ {/*swreg*/ 10,  1,  0,  1},
/* HWIF_PINIT_RLIST_F15             */ {/*swreg*/ 11,  5, 25,  1},
/* HWIF_PINIT_RLIST_F14             */ {/*swreg*/ 11,  5, 20,  1},
/* HWIF_PINIT_RLIST_F13             */ {/*swreg*/ 11,  5, 15,  1},
/* HWIF_PINIT_RLIST_F12             */ {/*swreg*/ 11,  5, 10,  1},
/* HWIF_PINIT_RLIST_F11             */ {/*swreg*/ 11,  5,  5,  1},
/* HWIF_PINIT_RLIST_F10             */ {/*swreg*/ 11,  5,  0,  1},
/* HWIF_ICOMP2_E                    */ {/*swreg*/ 11,  1, 24,  1},
/* HWIF_ISCALE2                     */ {/*swreg*/ 11,  8, 16,  1},
/* HWIF_ISHIFT2                     */ {/*swreg*/ 11, 16,  0,  1},
/* HWIF_DCT3_START_BIT              */ {/*swreg*/ 11,  6, 24,  1},
/* HWIF_DCT4_START_BIT              */ {/*swreg*/ 11,  6, 18,  1},
/* HWIF_DCT5_START_BIT              */ {/*swreg*/ 11,  6, 12,  1},
/* HWIF_DCT6_START_BIT              */ {/*swreg*/ 11,  6,  6,  1},
/* HWIF_DCT7_START_BIT              */ {/*swreg*/ 11,  6,  0,  1},
/* HWIF_TRANSFORM_MODE              */ {/*swreg*/ 11,  3, 27,  1},
/* HWIF_MCOMP_FILT_TYPE             */ {/*swreg*/ 11,  3,  8,  1},
/* HWIF_HIGH_PREC_MV_E              */ {/*swreg*/ 11,  1,  7,  1},
/* HWIF_COMP_PRED_MODE              */ {/*swreg*/ 11,  2,  4,  1},
/* HWIF_SYNC_MARKER_E               */ {/*swreg*/ 12,  1, 31,  1},
/* HWIF_MIN_CB_SIZE                 */ {/*swreg*/ 12,  3, 13,  1},
/* HWIF_MAX_CB_SIZE                 */ {/*swreg*/ 12,  3, 10,  1},
/* HWIF_MIN_PCM_SIZE                */ {/*swreg*/ 12,  3,  7,  1},
/* HWIF_MAX_PCM_SIZE                */ {/*swreg*/ 12,  3,  4,  1},
/* HWIF_PCM_E                       */ {/*swreg*/ 12,  1,  3,  1},
/* HWIF_TRANSFORM_SKIP_E            */ {/*swreg*/ 12,  1,  2,  1},
/* HWIF_TRANSQ_BYPASS_E             */ {/*swreg*/ 12,  1,  1,  1},
/* HWIF_REFPICLIST_MOD_E            */ {/*swreg*/ 12,  1,  0,  1},
/* HWIF_START_CODE_E                */ {/*swreg*/ 13,  1, 31,  1},
/* HWIF_INIT_QP                     */ {/*swreg*/ 13,  7, 24,  1},
/* HWIF_MIN_TRB_SIZE                */ {/*swreg*/ 13,  3, 13,  1},
/* HWIF_MAX_TRB_SIZE                */ {/*swreg*/ 13,  3, 10,  1},
/* HWIF_MAX_INTRA_HIERDEPTH         */ {/*swreg*/ 13,  3,  7,  1},
/* HWIF_MAX_INTER_HIERDEPTH         */ {/*swreg*/ 13,  3,  4,  1},
/* HWIF_PARALLEL_MERGE              */ {/*swreg*/ 13,  4,  0,  1},
/* HWIF_QP_DELTA_Y_DC               */ {/*swreg*/ 13,  6, 23,  1},
/* HWIF_QP_DELTA_CH_DC              */ {/*swreg*/ 13,  6, 17,  1},
/* HWIF_QP_DELTA_CH_AC              */ {/*swreg*/ 13,  6, 11,  1},
/* HWIF_LAST_SIGN_BIAS              */ {/*swreg*/ 13,  1, 10,  1},
/* HWIF_LOSSLESS_E                  */ {/*swreg*/ 13,  1,  9,  1},
/* HWIF_COMP_PRED_VAR_REF1          */ {/*swreg*/ 13,  2,  7,  1},
/* HWIF_COMP_PRED_VAR_REF0          */ {/*swreg*/ 13,  2,  5,  1},
/* HWIF_COMP_PRED_FIXED_REF         */ {/*swreg*/ 13,  2,  3,  1},
/* HWIF_SEGMENT_TEMP_UPD_E          */ {/*swreg*/ 13,  1,  2,  1},
/* HWIF_SEGMENT_UPD_E               */ {/*swreg*/ 13,  1,  1,  1},
/* HWIF_SEGMENT_E                   */ {/*swreg*/ 13,  1,  0,  1},
/* HWIF_INIT_RLIST_B2               */ {/*swreg*/ 14,  5, 25,  1},
/* HWIF_INIT_RLIST_F2               */ {/*swreg*/ 14,  5, 20,  1},
/* HWIF_INIT_RLIST_B1               */ {/*swreg*/ 14,  5, 15,  1},
/* HWIF_INIT_RLIST_F1               */ {/*swreg*/ 14,  5, 10,  1},
/* HWIF_INIT_RLIST_B0               */ {/*swreg*/ 14,  5,  5,  1},
/* HWIF_INIT_RLIST_F0               */ {/*swreg*/ 14,  5,  0,  1},
/* HWIF_FILT_LEVEL                  */ {/*swreg*/ 14,  6, 18,  1},
/* HWIF_REFPIC_SEG0                 */ {/*swreg*/ 14,  3, 15,  1},
/* HWIF_SKIP_SEG0                   */ {/*swreg*/ 14,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG0             */ {/*swreg*/ 14,  6,  8,  1},
/* HWIF_QUANT_SEG0                  */ {/*swreg*/ 14,  8,  0,  1},
/* HWIF_JPEG_SLICE_H                */ {/*swreg*/ 15,  8,  0,  1},
/* HWIF_INIT_RLIST_B5               */ {/*swreg*/ 15,  5, 25,  1},
/* HWIF_INIT_RLIST_F5               */ {/*swreg*/ 15,  5, 20,  1},
/* HWIF_INIT_RLIST_B4               */ {/*swreg*/ 15,  5, 15,  1},
/* HWIF_INIT_RLIST_F4               */ {/*swreg*/ 15,  5, 10,  1},
/* HWIF_INIT_RLIST_B3               */ {/*swreg*/ 15,  5,  5,  1},
/* HWIF_INIT_RLIST_F3               */ {/*swreg*/ 15,  5,  0,  1},
/* HWIF_REFPIC_SEG1                 */ {/*swreg*/ 15,  3, 15,  1},
/* HWIF_SKIP_SEG1                   */ {/*swreg*/ 15,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG1             */ {/*swreg*/ 15,  6,  8,  1},
/* HWIF_QUANT_SEG1                  */ {/*swreg*/ 15,  8,  0,  1},
/* HWIF_AC1_CODE6_CNT               */ {/*swreg*/ 16,  7, 24,  1},
/* HWIF_AC1_CODE5_CNT               */ {/*swreg*/ 16,  6, 16,  1},
/* HWIF_AC1_CODE4_CNT               */ {/*swreg*/ 16,  5, 11,  1},
/* HWIF_AC1_CODE3_CNT               */ {/*swreg*/ 16,  4,  7,  1},
/* HWIF_AC1_CODE2_CNT               */ {/*swreg*/ 16,  3,  3,  1},
/* HWIF_AC1_CODE1_CNT               */ {/*swreg*/ 16,  2,  0,  1},
/* HWIF_INIT_RLIST_B8               */ {/*swreg*/ 16,  5, 25,  1},
/* HWIF_INIT_RLIST_F8               */ {/*swreg*/ 16,  5, 20,  1},
/* HWIF_INIT_RLIST_B7               */ {/*swreg*/ 16,  5, 15,  1},
/* HWIF_INIT_RLIST_F7               */ {/*swreg*/ 16,  5, 10,  1},
/* HWIF_INIT_RLIST_B6               */ {/*swreg*/ 16,  5,  5,  1},
/* HWIF_INIT_RLIST_F6               */ {/*swreg*/ 16,  5,  0,  1},
/* HWIF_REFPIC_SEG2                 */ {/*swreg*/ 16,  3, 15,  1},
/* HWIF_SKIP_SEG2                   */ {/*swreg*/ 16,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG2             */ {/*swreg*/ 16,  6,  8,  1},
/* HWIF_QUANT_SEG2                  */ {/*swreg*/ 16,  8,  0,  1},
/* HWIF_AC1_CODE10_CNT              */ {/*swreg*/ 17,  8, 24,  1},
/* HWIF_AC1_CODE9_CNT               */ {/*swreg*/ 17,  8, 16,  1},
/* HWIF_AC1_CODE8_CNT               */ {/*swreg*/ 17,  8,  8,  1},
/* HWIF_AC1_CODE7_CNT               */ {/*swreg*/ 17,  8,  0,  1},
/* HWIF_INIT_RLIST_B11              */ {/*swreg*/ 17,  5, 25,  1},
/* HWIF_INIT_RLIST_F11              */ {/*swreg*/ 17,  5, 20,  1},
/* HWIF_INIT_RLIST_B10              */ {/*swreg*/ 17,  5, 15,  1},
/* HWIF_INIT_RLIST_F10              */ {/*swreg*/ 17,  5, 10,  1},
/* HWIF_INIT_RLIST_B9               */ {/*swreg*/ 17,  5,  5,  1},
/* HWIF_INIT_RLIST_F9               */ {/*swreg*/ 17,  5,  0,  1},
/* HWIF_REFPIC_SEG3                 */ {/*swreg*/ 17,  3, 15,  1},
/* HWIF_SKIP_SEG3                   */ {/*swreg*/ 17,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG3             */ {/*swreg*/ 17,  6,  8,  1},
/* HWIF_QUANT_SEG3                  */ {/*swreg*/ 17,  8,  0,  1},
/* HWIF_PIC_HEADER_LEN              */ {/*swreg*/ 18, 16, 16,  1},
/* HWIF_PIC_4MV_E                   */ {/*swreg*/ 18,  1, 13,  1},
/* HWIF_RANGE_RED_REF_E             */ {/*swreg*/ 18,  1, 11,  1},
/* HWIF_VC1_DIFMV_RANGE             */ {/*swreg*/ 18,  2,  9,  1},
/* HWIF_MV_RANGE                    */ {/*swreg*/ 18,  2,  6,  1},
/* HWIF_OVERLAP_E                   */ {/*swreg*/ 18,  1,  5,  1},
/* HWIF_OVERLAP_METHOD              */ {/*swreg*/ 18,  2,  3,  1},
/* HWIF_ALT_SCAN_FLAG_E             */ {/*swreg*/ 18,  1, 19,  1},
/* HWIF_FCODE_FWD_HOR               */ {/*swreg*/ 18,  4, 15,  1},
/* HWIF_FCODE_FWD_VER               */ {/*swreg*/ 18,  4, 11,  1},
/* HWIF_FCODE_BWD_HOR               */ {/*swreg*/ 18,  4,  7,  1},
/* HWIF_FCODE_BWD_VER               */ {/*swreg*/ 18,  4,  3,  1},
/* HWIF_MV_ACCURACY_FWD             */ {/*swreg*/ 18,  1,  2,  1},
/* HWIF_MV_ACCURACY_BWD             */ {/*swreg*/ 18,  1,  1,  1},
/* HWIF_MPEG4_VC1_RC                */ {/*swreg*/ 18,  1,  1,  1},
/* HWIF_PREV_ANC_TYPE               */ {/*swreg*/ 18,  1,  0,  1},
/* HWIF_AC1_CODE14_CNT              */ {/*swreg*/ 18,  8, 24,  1},
/* HWIF_AC1_CODE13_CNT              */ {/*swreg*/ 18,  8, 16,  1},
/* HWIF_AC1_CODE12_CNT              */ {/*swreg*/ 18,  8,  8,  1},
/* HWIF_AC1_CODE11_CNT              */ {/*swreg*/ 18,  8,  0,  1},
/* HWIF_INIT_RLIST_B14              */ {/*swreg*/ 18,  5, 25,  1},
/* HWIF_INIT_RLIST_F14              */ {/*swreg*/ 18,  5, 20,  1},
/* HWIF_INIT_RLIST_B13              */ {/*swreg*/ 18,  5, 15,  1},
/* HWIF_INIT_RLIST_F13              */ {/*swreg*/ 18,  5, 10,  1},
/* HWIF_INIT_RLIST_B12              */ {/*swreg*/ 18,  5,  5,  1},
/* HWIF_INIT_RLIST_F12              */ {/*swreg*/ 18,  5,  0,  1},
/* HWIF_REFPIC_SEG4                 */ {/*swreg*/ 18,  3, 15,  1},
/* HWIF_SKIP_SEG4                   */ {/*swreg*/ 18,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG4             */ {/*swreg*/ 18,  6,  8,  1},
/* HWIF_QUANT_SEG4                  */ {/*swreg*/ 18,  8,  0,  1},
/* HWIF_TRB_PER_TRD_D0              */ {/*swreg*/ 19, 27,  0,  1},
/* HWIF_ICOMP3_E                    */ {/*swreg*/ 19,  1, 24,  1},
/* HWIF_ISCALE3                     */ {/*swreg*/ 19,  8, 16,  1},
/* HWIF_ISHIFT3                     */ {/*swreg*/ 19, 16,  0,  1},
/* HWIF_AC2_CODE4_CNT               */ {/*swreg*/ 19,  5, 27,  1},
/* HWIF_AC2_CODE3_CNT               */ {/*swreg*/ 19,  4, 23,  1},
/* HWIF_AC2_CODE2_CNT               */ {/*swreg*/ 19,  3, 19,  1},
/* HWIF_AC2_CODE1_CNT               */ {/*swreg*/ 19,  2, 16,  1},
/* HWIF_AC1_CODE16_CNT              */ {/*swreg*/ 19,  8,  8,  1},
/* HWIF_AC1_CODE15_CNT              */ {/*swreg*/ 19,  8,  0,  1},
/* HWIF_SCAN_MAP_1                  */ {/*swreg*/ 19,  6, 24,  1},
/* HWIF_SCAN_MAP_2                  */ {/*swreg*/ 19,  6, 18,  1},
/* HWIF_SCAN_MAP_3                  */ {/*swreg*/ 19,  6, 12,  1},
/* HWIF_SCAN_MAP_4                  */ {/*swreg*/ 19,  6,  6,  1},
/* HWIF_SCAN_MAP_5                  */ {/*swreg*/ 19,  6,  0,  1},
/* HWIF_INIT_RLIST_B15              */ {/*swreg*/ 19,  5,  5,  1},
/* HWIF_INIT_RLIST_F15              */ {/*swreg*/ 19,  5,  0,  1},
/* HWIF_REFPIC_SEG5                 */ {/*swreg*/ 19,  3, 15,  1},
/* HWIF_SKIP_SEG5                   */ {/*swreg*/ 19,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG5             */ {/*swreg*/ 19,  6,  8,  1},
/* HWIF_QUANT_SEG5                  */ {/*swreg*/ 19,  8,  0,  1},
/* HWIF_TRB_PER_TRD_DM1             */ {/*swreg*/ 20, 27,  0,  1},
/* HWIF_ICOMP4_E                    */ {/*swreg*/ 20,  1, 24,  1},
/* HWIF_ISCALE4                     */ {/*swreg*/ 20,  8, 16,  1},
/* HWIF_ISHIFT4                     */ {/*swreg*/ 20, 16,  0,  1},
/* HWIF_AC2_CODE8_CNT               */ {/*swreg*/ 20,  8, 24,  1},
/* HWIF_AC2_CODE7_CNT               */ {/*swreg*/ 20,  8, 16,  1},
/* HWIF_AC2_CODE6_CNT               */ {/*swreg*/ 20,  7,  8,  1},
/* HWIF_AC2_CODE5_CNT               */ {/*swreg*/ 20,  6,  0,  1},
/* HWIF_SCAN_MAP_6                  */ {/*swreg*/ 20,  6, 24,  1},
/* HWIF_SCAN_MAP_7                  */ {/*swreg*/ 20,  6, 18,  1},
/* HWIF_SCAN_MAP_8                  */ {/*swreg*/ 20,  6, 12,  1},
/* HWIF_SCAN_MAP_9                  */ {/*swreg*/ 20,  6,  6,  1},
/* HWIF_SCAN_MAP_10                 */ {/*swreg*/ 20,  6,  0,  1},
/* HWIF_PARTIAL_CTB_X               */ {/*swreg*/ 20,  1, 31,  1},
/* HWIF_PARTIAL_CTB_Y               */ {/*swreg*/ 20,  1, 30,  1},
/* HWIF_PIC_WIDTH_4X4               */ {/*swreg*/ 20, 12, 16,  1},
/* HWIF_PIC_HEIGHT_4X4              */ {/*swreg*/ 20, 12,  0,  1},
/* HWIF_Y_STRIDE_POW2               */ {/*swreg*/ 21,  5, 27,  1},
/* HWIF_C_STRIDE_POW2               */ {/*swreg*/ 21,  5, 22,  1},
/* HWIF_TRB_PER_TRD_D1              */ {/*swreg*/ 21, 27,  0,  1},
/* HWIF_AC2_CODE12_CNT              */ {/*swreg*/ 21,  8, 24,  1},
/* HWIF_AC2_CODE11_CNT              */ {/*swreg*/ 21,  8, 16,  1},
/* HWIF_AC2_CODE10_CNT              */ {/*swreg*/ 21,  8,  8,  1},
/* HWIF_AC2_CODE9_CNT               */ {/*swreg*/ 21,  8,  0,  1},
/* HWIF_SCAN_MAP_11                 */ {/*swreg*/ 21,  6, 24,  1},
/* HWIF_SCAN_MAP_12                 */ {/*swreg*/ 21,  6, 18,  1},
/* HWIF_SCAN_MAP_13                 */ {/*swreg*/ 21,  6, 12,  1},
/* HWIF_SCAN_MAP_14                 */ {/*swreg*/ 21,  6,  6,  1},
/* HWIF_SCAN_MAP_15                 */ {/*swreg*/ 21,  6,  0,  1},
/* HWIF_AC2_CODE16_CNT              */ {/*swreg*/ 22,  8, 24,  1},
/* HWIF_AC2_CODE15_CNT              */ {/*swreg*/ 22,  8, 16,  1},
/* HWIF_AC2_CODE14_CNT              */ {/*swreg*/ 22,  8,  8,  1},
/* HWIF_AC2_CODE13_CNT              */ {/*swreg*/ 22,  8,  0,  1},
/* HWIF_SCAN_MAP_16                 */ {/*swreg*/ 22,  6, 24,  1},
/* HWIF_SCAN_MAP_17                 */ {/*swreg*/ 22,  6, 18,  1},
/* HWIF_SCAN_MAP_18                 */ {/*swreg*/ 22,  6, 12,  1},
/* HWIF_SCAN_MAP_19                 */ {/*swreg*/ 22,  6,  6,  1},
/* HWIF_SCAN_MAP_20                 */ {/*swreg*/ 22,  6,  0,  1},
/* HWIF_DC1_CODE8_CNT               */ {/*swreg*/ 23,  4, 28,  1},
/* HWIF_DC1_CODE7_CNT               */ {/*swreg*/ 23,  4, 24,  1},
/* HWIF_DC1_CODE6_CNT               */ {/*swreg*/ 23,  4, 20,  1},
/* HWIF_DC1_CODE5_CNT               */ {/*swreg*/ 23,  4, 16,  1},
/* HWIF_DC1_CODE4_CNT               */ {/*swreg*/ 23,  4, 12,  1},
/* HWIF_DC1_CODE3_CNT               */ {/*swreg*/ 23,  4,  8,  1},
/* HWIF_DC1_CODE2_CNT               */ {/*swreg*/ 23,  3,  4,  1},
/* HWIF_DC1_CODE1_CNT               */ {/*swreg*/ 23,  2,  0,  1},
/* HWIF_SCAN_MAP_21                 */ {/*swreg*/ 23,  6, 24,  1},
/* HWIF_SCAN_MAP_22                 */ {/*swreg*/ 23,  6, 18,  1},
/* HWIF_SCAN_MAP_23                 */ {/*swreg*/ 23,  6, 12,  1},
/* HWIF_SCAN_MAP_24                 */ {/*swreg*/ 23,  6,  6,  1},
/* HWIF_SCAN_MAP_25                 */ {/*swreg*/ 23,  6,  0,  1},
/* HWIF_DC1_CODE16_CNT              */ {/*swreg*/ 24,  4, 28,  1},
/* HWIF_DC1_CODE15_CNT              */ {/*swreg*/ 24,  4, 24,  1},
/* HWIF_DC1_CODE14_CNT              */ {/*swreg*/ 24,  4, 20,  1},
/* HWIF_DC1_CODE13_CNT              */ {/*swreg*/ 24,  4, 16,  1},
/* HWIF_DC1_CODE12_CNT              */ {/*swreg*/ 24,  4, 12,  1},
/* HWIF_DC1_CODE11_CNT              */ {/*swreg*/ 24,  4,  8,  1},
/* HWIF_DC1_CODE10_CNT              */ {/*swreg*/ 24,  4,  4,  1},
/* HWIF_DC1_CODE9_CNT               */ {/*swreg*/ 24,  4,  0,  1},
/* HWIF_SCAN_MAP_26                 */ {/*swreg*/ 24,  6, 24,  1},
/* HWIF_SCAN_MAP_27                 */ {/*swreg*/ 24,  6, 18,  1},
/* HWIF_SCAN_MAP_28                 */ {/*swreg*/ 24,  6, 12,  1},
/* HWIF_SCAN_MAP_29                 */ {/*swreg*/ 24,  6,  6,  1},
/* HWIF_SCAN_MAP_30                 */ {/*swreg*/ 24,  6,  0,  1},
/* HWIF_DC2_CODE8_CNT               */ {/*swreg*/ 25,  4, 28,  1},
/* HWIF_DC2_CODE7_CNT               */ {/*swreg*/ 25,  4, 24,  1},
/* HWIF_DC2_CODE6_CNT               */ {/*swreg*/ 25,  4, 20,  1},
/* HWIF_DC2_CODE5_CNT               */ {/*swreg*/ 25,  4, 16,  1},
/* HWIF_DC2_CODE4_CNT               */ {/*swreg*/ 25,  4, 12,  1},
/* HWIF_DC2_CODE3_CNT               */ {/*swreg*/ 25,  4,  8,  1},
/* HWIF_DC2_CODE2_CNT               */ {/*swreg*/ 25,  3,  4,  1},
/* HWIF_DC2_CODE1_CNT               */ {/*swreg*/ 25,  2,  0,  1},
/* HWIF_SCAN_MAP_31                 */ {/*swreg*/ 25,  6, 24,  1},
/* HWIF_SCAN_MAP_32                 */ {/*swreg*/ 25,  6, 18,  1},
/* HWIF_SCAN_MAP_33                 */ {/*swreg*/ 25,  6, 12,  1},
/* HWIF_SCAN_MAP_34                 */ {/*swreg*/ 25,  6,  6,  1},
/* HWIF_SCAN_MAP_35                 */ {/*swreg*/ 25,  6,  0,  1},
/* HWIF_DC2_CODE16_CNT              */ {/*swreg*/ 26,  4, 28,  1},
/* HWIF_DC2_CODE15_CNT              */ {/*swreg*/ 26,  4, 24,  1},
/* HWIF_DC2_CODE14_CNT              */ {/*swreg*/ 26,  4, 20,  1},
/* HWIF_DC2_CODE13_CNT              */ {/*swreg*/ 26,  4, 16,  1},
/* HWIF_DC2_CODE12_CNT              */ {/*swreg*/ 26,  4, 12,  1},
/* HWIF_DC2_CODE11_CNT              */ {/*swreg*/ 26,  4,  8,  1},
/* HWIF_DC2_CODE10_CNT              */ {/*swreg*/ 26,  4,  4,  1},
/* HWIF_DC2_CODE9_CNT               */ {/*swreg*/ 26,  4,  0,  1},
/* HWIF_SCAN_MAP_36                 */ {/*swreg*/ 26,  6, 24,  1},
/* HWIF_SCAN_MAP_37                 */ {/*swreg*/ 26,  6, 18,  1},
/* HWIF_SCAN_MAP_38                 */ {/*swreg*/ 26,  6, 12,  1},
/* HWIF_SCAN_MAP_39                 */ {/*swreg*/ 26,  6,  6,  1},
/* HWIF_SCAN_MAP_40                 */ {/*swreg*/ 26,  6,  0,  1},
/* HWIF_DC3_CODE8_CNT               */ {/*swreg*/ 27,  4, 28,  1},
/* HWIF_DC3_CODE7_CNT               */ {/*swreg*/ 27,  4, 24,  1},
/* HWIF_DC3_CODE6_CNT               */ {/*swreg*/ 27,  4, 20,  1},
/* HWIF_DC3_CODE5_CNT               */ {/*swreg*/ 27,  4, 16,  1},
/* HWIF_DC3_CODE4_CNT               */ {/*swreg*/ 27,  4, 12,  1},
/* HWIF_DC3_CODE3_CNT               */ {/*swreg*/ 27,  4,  8,  1},
/* HWIF_DC3_CODE2_CNT               */ {/*swreg*/ 27,  3,  4,  1},
/* HWIF_DC3_CODE1_CNT               */ {/*swreg*/ 27,  2,  0,  1},
/* HWIF_REF_INVD_CUR_1              */ {/*swreg*/ 28, 16, 16,  1},
/* HWIF_REF_INVD_CUR_0              */ {/*swreg*/ 28, 16,  0,  1},
/* HWIF_DC3_CODE16_CNT              */ {/*swreg*/ 28,  4, 28,  1},
/* HWIF_DC3_CODE15_CNT              */ {/*swreg*/ 28,  4, 24,  1},
/* HWIF_DC3_CODE14_CNT              */ {/*swreg*/ 28,  4, 20,  1},
/* HWIF_DC3_CODE13_CNT              */ {/*swreg*/ 28,  4, 16,  1},
/* HWIF_DC3_CODE12_CNT              */ {/*swreg*/ 28,  4, 12,  1},
/* HWIF_DC3_CODE11_CNT              */ {/*swreg*/ 28,  4,  8,  1},
/* HWIF_DC3_CODE10_CNT              */ {/*swreg*/ 28,  4,  4,  1},
/* HWIF_DC3_CODE9_CNT               */ {/*swreg*/ 28,  4,  0,  1},
/* HWIF_SCAN_MAP_41                 */ {/*swreg*/ 28,  6, 24,  1},
/* HWIF_SCAN_MAP_42                 */ {/*swreg*/ 28,  6, 18,  1},
/* HWIF_SCAN_MAP_43                 */ {/*swreg*/ 28,  6, 12,  1},
/* HWIF_SCAN_MAP_44                 */ {/*swreg*/ 28,  6,  6,  1},
/* HWIF_SCAN_MAP_45                 */ {/*swreg*/ 28,  6,  0,  1},
/* HWIF_REF_INVD_CUR_3              */ {/*swreg*/ 29, 16, 16,  1},
/* HWIF_REF_INVD_CUR_2              */ {/*swreg*/ 29, 16,  0,  1},
/* HWIF_SCAN_MAP_46                 */ {/*swreg*/ 29,  6, 24,  1},
/* HWIF_SCAN_MAP_47                 */ {/*swreg*/ 29,  6, 18,  1},
/* HWIF_SCAN_MAP_48                 */ {/*swreg*/ 29,  6, 12,  1},
/* HWIF_SCAN_MAP_49                 */ {/*swreg*/ 29,  6,  6,  1},
/* HWIF_SCAN_MAP_50                 */ {/*swreg*/ 29,  6,  0,  1},
/* HWIF_REFER1_NBR                  */ {/*swreg*/ 30, 16, 16,  1},
/* HWIF_REFER0_NBR                  */ {/*swreg*/ 30, 16,  0,  1},
/* HWIF_REF_DIST_CUR_1              */ {/*swreg*/ 30, 16, 16,  1},
/* HWIF_REF_DIST_CUR_0              */ {/*swreg*/ 30, 16,  0,  1},
/* HWIF_FILT_TYPE                   */ {/*swreg*/ 30,  1, 31,  1},
/* HWIF_FILT_SHARPNESS              */ {/*swreg*/ 30,  3, 28,  1},
/* HWIF_FILT_MB_ADJ_0               */ {/*swreg*/ 30,  7, 21,  1},
/* HWIF_FILT_MB_ADJ_1               */ {/*swreg*/ 30,  7, 14,  1},
/* HWIF_FILT_MB_ADJ_2               */ {/*swreg*/ 30,  7,  7,  1},
/* HWIF_FILT_MB_ADJ_3               */ {/*swreg*/ 30,  7,  0,  1},
/* HWIF_REFER3_NBR                  */ {/*swreg*/ 31, 16, 16,  1},
/* HWIF_REFER2_NBR                  */ {/*swreg*/ 31, 16,  0,  1},
/* HWIF_SCAN_MAP_51                 */ {/*swreg*/ 31,  6, 24,  1},
/* HWIF_SCAN_MAP_52                 */ {/*swreg*/ 31,  6, 18,  1},
/* HWIF_SCAN_MAP_53                 */ {/*swreg*/ 31,  6, 12,  1},
/* HWIF_SCAN_MAP_54                 */ {/*swreg*/ 31,  6,  6,  1},
/* HWIF_SCAN_MAP_55                 */ {/*swreg*/ 31,  6,  0,  1},
/* HWIF_REF_DIST_CUR_3              */ {/*swreg*/ 31, 16, 16,  1},
/* HWIF_REF_DIST_CUR_2              */ {/*swreg*/ 31, 16,  0,  1},
/* HWIF_REFPIC_SEG6                 */ {/*swreg*/ 31,  3, 15,  1},
/* HWIF_SKIP_SEG6                   */ {/*swreg*/ 31,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG6             */ {/*swreg*/ 31,  6,  8,  1},
/* HWIF_QUANT_SEG6                  */ {/*swreg*/ 31,  8,  0,  1},
/* HWIF_REFER5_NBR                  */ {/*swreg*/ 32, 16, 16,  1},
/* HWIF_REFER4_NBR                  */ {/*swreg*/ 32, 16,  0,  1},
/* HWIF_SCAN_MAP_56                 */ {/*swreg*/ 32,  6, 24,  1},
/* HWIF_SCAN_MAP_57                 */ {/*swreg*/ 32,  6, 18,  1},
/* HWIF_SCAN_MAP_58                 */ {/*swreg*/ 32,  6, 12,  1},
/* HWIF_SCAN_MAP_59                 */ {/*swreg*/ 32,  6,  6,  1},
/* HWIF_SCAN_MAP_60                 */ {/*swreg*/ 32,  6,  0,  1},
/* HWIF_REF_INVD_COL_1              */ {/*swreg*/ 32, 16, 16,  1},
/* HWIF_REF_INVD_COL_0              */ {/*swreg*/ 32, 16,  0,  1},
/* HWIF_FILT_LEVEL_0                */ {/*swreg*/ 32,  6, 18,  1},
/* HWIF_FILT_LEVEL_1                */ {/*swreg*/ 32,  6, 12,  1},
/* HWIF_FILT_LEVEL_2                */ {/*swreg*/ 32,  6,  6,  1},
/* HWIF_FILT_LEVEL_3                */ {/*swreg*/ 32,  6,  0,  1},
/* HWIF_REFPIC_SEG7                 */ {/*swreg*/ 32,  3, 15,  1},
/* HWIF_SKIP_SEG7                   */ {/*swreg*/ 32,  1, 14,  1},
/* HWIF_FILT_LEVEL_SEG7             */ {/*swreg*/ 32,  6,  8,  1},
/* HWIF_QUANT_SEG7                  */ {/*swreg*/ 32,  8,  0,  1},
/* HWIF_REFER7_NBR                  */ {/*swreg*/ 33, 16, 16,  1},
/* HWIF_REFER6_NBR                  */ {/*swreg*/ 33, 16,  0,  1},
/* HWIF_SCAN_MAP_61                 */ {/*swreg*/ 33,  6, 24,  1},
/* HWIF_SCAN_MAP_62                 */ {/*swreg*/ 33,  6, 18,  1},
/* HWIF_SCAN_MAP_63                 */ {/*swreg*/ 33,  6, 12,  1},
/* HWIF_REF_INVD_COL_3              */ {/*swreg*/ 33, 16, 16,  1},
/* HWIF_REF_INVD_COL_2              */ {/*swreg*/ 33, 16,  0,  1},
/* HWIF_QUANT_DELTA_0               */ {/*swreg*/ 33,  5, 27,  1},
/* HWIF_QUANT_DELTA_1               */ {/*swreg*/ 33,  5, 22,  1},
/* HWIF_QUANT_0                     */ {/*swreg*/ 33, 11, 11,  1},
/* HWIF_QUANT_1                     */ {/*swreg*/ 33, 11,  0,  1},
/* HWIF_LREF_WIDTH                  */ {/*swreg*/ 33, 16, 16,  1},
/* HWIF_LREF_HEIGHT                 */ {/*swreg*/ 33, 16,  0,  1},
/* HWIF_REFER9_NBR                  */ {/*swreg*/ 34, 16, 16,  1},
/* HWIF_REFER8_NBR                  */ {/*swreg*/ 34, 16,  0,  1},
/* HWIF_PRED_BC_TAP_0_3             */ {/*swreg*/ 34, 10, 22,  1},
/* HWIF_PRED_BC_TAP_1_0             */ {/*swreg*/ 34, 10, 12,  1},
/* HWIF_PRED_BC_TAP_1_1             */ {/*swreg*/ 34, 10,  2,  1},
/* HWIF_GREF_WIDTH                  */ {/*swreg*/ 34, 16, 16,  1},
/* HWIF_GREF_HEIGHT                 */ {/*swreg*/ 34, 16,  0,  1},
/* HWIF_REFER11_NBR                 */ {/*swreg*/ 35, 16, 16,  1},
/* HWIF_REFER10_NBR                 */ {/*swreg*/ 35, 16,  0,  1},
/* HWIF_PRED_BC_TAP_1_2             */ {/*swreg*/ 35, 10, 22,  1},
/* HWIF_PRED_BC_TAP_1_3             */ {/*swreg*/ 35, 10, 12,  1},
/* HWIF_PRED_BC_TAP_2_0             */ {/*swreg*/ 35, 10,  2,  1},
/* HWIF_AREF_WIDTH                  */ {/*swreg*/ 35, 16, 16,  1},
/* HWIF_AREF_HEIGHT                 */ {/*swreg*/ 35, 16,  0,  1},
/* HWIF_REFER13_NBR                 */ {/*swreg*/ 36, 16, 16,  1},
/* HWIF_REFER12_NBR                 */ {/*swreg*/ 36, 16,  0,  1},
/* HWIF_PRED_BC_TAP_2_1             */ {/*swreg*/ 36, 10, 22,  1},
/* HWIF_PRED_BC_TAP_2_2             */ {/*swreg*/ 36, 10, 12,  1},
/* HWIF_PRED_BC_TAP_2_3             */ {/*swreg*/ 36, 10,  2,  1},
/* HWIF_LREF_HOR_SCALE              */ {/*swreg*/ 36, 16, 16,  1},
/* HWIF_LREF_VER_SCALE              */ {/*swreg*/ 36, 16,  0,  1},
/* HWIF_REFER15_NBR                 */ {/*swreg*/ 37, 16, 16,  1},
/* HWIF_REFER14_NBR                 */ {/*swreg*/ 37, 16,  0,  1},
/* HWIF_PRED_BC_TAP_3_0             */ {/*swreg*/ 37, 10, 22,  1},
/* HWIF_PRED_BC_TAP_3_1             */ {/*swreg*/ 37, 10, 12,  1},
/* HWIF_PRED_BC_TAP_3_2             */ {/*swreg*/ 37, 10,  2,  1},
/* HWIF_GREF_HOR_SCALE              */ {/*swreg*/ 37, 16, 16,  1},
/* HWIF_GREF_VER_SCALE              */ {/*swreg*/ 37, 16,  0,  1},
/* HWIF_REFER_LTERM_E               */ {/*swreg*/ 38, 32,  0,  1},
/* HWIF_PRED_BC_TAP_3_3             */ {/*swreg*/ 38, 10, 22,  1},
/* HWIF_PRED_BC_TAP_4_0             */ {/*swreg*/ 38, 10, 12,  1},
/* HWIF_PRED_BC_TAP_4_1             */ {/*swreg*/ 38, 10,  2,  1},
/* HWIF_AREF_HOR_SCALE              */ {/*swreg*/ 38, 16, 16,  1},
/* HWIF_AREF_VER_SCALE              */ {/*swreg*/ 38, 16,  0,  1},
/* HWIF_REFER_VALID_E               */ {/*swreg*/ 39, 32,  0,  1},
/* HWIF_PRED_BC_TAP_4_2             */ {/*swreg*/ 39, 10, 22,  1},
/* HWIF_PRED_BC_TAP_4_3             */ {/*swreg*/ 39, 10, 12,  1},
/* HWIF_PRED_BC_TAP_5_0             */ {/*swreg*/ 39, 10,  2,  1},
/* HWIF_BINIT_RLIST_B2              */ {/*swreg*/ 42,  5, 25,  1},
/* HWIF_BINIT_RLIST_F2              */ {/*swreg*/ 42,  5, 20,  1},
/* HWIF_BINIT_RLIST_B1              */ {/*swreg*/ 42,  5, 15,  1},
/* HWIF_BINIT_RLIST_F1              */ {/*swreg*/ 42,  5, 10,  1},
/* HWIF_BINIT_RLIST_B0              */ {/*swreg*/ 42,  5,  5,  1},
/* HWIF_BINIT_RLIST_F0              */ {/*swreg*/ 42,  5,  0,  1},
/* HWIF_PRED_BC_TAP_5_1             */ {/*swreg*/ 42, 10, 22,  1},
/* HWIF_PRED_BC_TAP_5_2             */ {/*swreg*/ 42, 10, 12,  1},
/* HWIF_PRED_BC_TAP_5_3             */ {/*swreg*/ 42, 10,  2,  1},
/* HWIF_WEIGHT_QP_1                 */ {/*swreg*/ 42,  8, 24,  1},
/* HWIF_REF_DELTA_COL_0             */ {/*swreg*/ 42,  3, 21,  1},
/* HWIF_REF_DELTA_COL_1             */ {/*swreg*/ 42,  3, 18,  1},
/* HWIF_REF_DELTA_COL_2             */ {/*swreg*/ 42,  3, 15,  1},
/* HWIF_REF_DELTA_COL_3             */ {/*swreg*/ 42,  3, 12,  1},
/* HWIF_REF_DELTA_CUR_0             */ {/*swreg*/ 42,  3,  9,  1},
/* HWIF_REF_DELTA_CUR_1             */ {/*swreg*/ 42,  3,  6,  1},
/* HWIF_REF_DELTA_CUR_2             */ {/*swreg*/ 42,  3,  3,  1},
/* HWIF_REF_DELTA_CUR_3             */ {/*swreg*/ 42,  3,  0,  1},
/* HWIF_LREF_Y_STRIDE               */ {/*swreg*/ 42, 16, 16,  1},
/* HWIF_LREF_C_STRIDE               */ {/*swreg*/ 42, 16,  0,  1},
/* HWIF_BINIT_RLIST_B5              */ {/*swreg*/ 43,  5, 25,  1},
/* HWIF_BINIT_RLIST_F5              */ {/*swreg*/ 43,  5, 20,  1},
/* HWIF_BINIT_RLIST_B4              */ {/*swreg*/ 43,  5, 15,  1},
/* HWIF_BINIT_RLIST_F4              */ {/*swreg*/ 43,  5, 10,  1},
/* HWIF_BINIT_RLIST_B3              */ {/*swreg*/ 43,  5,  5,  1},
/* HWIF_BINIT_RLIST_F3              */ {/*swreg*/ 43,  5,  0,  1},
/* HWIF_PRED_BC_TAP_6_0             */ {/*swreg*/ 43, 10, 22,  1},
/* HWIF_PRED_BC_TAP_6_1             */ {/*swreg*/ 43, 10, 12,  1},
/* HWIF_PRED_BC_TAP_6_2             */ {/*swreg*/ 43, 10,  2,  1},
/* HWIF_WEIGHT_QP_2                 */ {/*swreg*/ 43,  8, 24,  1},
/* HWIF_WEIGHT_QP_3                 */ {/*swreg*/ 43,  8, 16,  1},
/* HWIF_WEIGHT_QP_4                 */ {/*swreg*/ 43,  8,  8,  1},
/* HWIF_WEIGHT_QP_5                 */ {/*swreg*/ 43,  8,  0,  1},
/* HWIF_GREF_Y_STRIDE               */ {/*swreg*/ 43, 16, 16,  1},
/* HWIF_GREF_C_STRIDE               */ {/*swreg*/ 43, 16,  0,  1},
/* HWIF_BINIT_RLIST_B8              */ {/*swreg*/ 44,  5, 25,  1},
/* HWIF_BINIT_RLIST_F8              */ {/*swreg*/ 44,  5, 20,  1},
/* HWIF_BINIT_RLIST_B7              */ {/*swreg*/ 44,  5, 15,  1},
/* HWIF_BINIT_RLIST_F7              */ {/*swreg*/ 44,  5, 10,  1},
/* HWIF_BINIT_RLIST_B6              */ {/*swreg*/ 44,  5,  5,  1},
/* HWIF_BINIT_RLIST_F6              */ {/*swreg*/ 44,  5,  0,  1},
/* HWIF_PRED_BC_TAP_6_3             */ {/*swreg*/ 44, 10, 22,  1},
/* HWIF_PRED_BC_TAP_7_0             */ {/*swreg*/ 44, 10, 12,  1},
/* HWIF_PRED_BC_TAP_7_1             */ {/*swreg*/ 44, 10,  2,  1},
/* HWIF_DEC_AVSP_ENA                */ {/*swreg*/ 44,  1, 26,  1},
/* HWIF_WEIGHT_QP_E                 */ {/*swreg*/ 44,  1, 25,  1},
/* HWIF_WEIGHT_QP_MODEL             */ {/*swreg*/ 44,  2, 23,  1},
/* HWIF_AVS_AEC_E                   */ {/*swreg*/ 44,  1, 22,  1},
/* HWIF_NO_FWD_REF_E                */ {/*swreg*/ 44,  1, 21,  1},
/* HWIF_PB_FIELD_ENHANCED_E         */ {/*swreg*/ 44,  1, 20,  1},
/* HWIF_QP_DELTA_CB                 */ {/*swreg*/ 44,  6, 14,  1},
/* HWIF_QP_DELTA_CR                 */ {/*swreg*/ 44,  6,  8,  1},
/* HWIF_WEIGHT_QP_0                 */ {/*swreg*/ 44,  8,  0,  1},
/* HWIF_AREF_Y_STRIDE               */ {/*swreg*/ 44, 16, 16,  1},
/* HWIF_AREF_C_STRIDE               */ {/*swreg*/ 44, 16,  0,  1},
/* HWIF_BINIT_RLIST_B11             */ {/*swreg*/ 45,  5, 25,  1},
/* HWIF_BINIT_RLIST_F11             */ {/*swreg*/ 45,  5, 20,  1},
/* HWIF_BINIT_RLIST_B10             */ {/*swreg*/ 45,  5, 15,  1},
/* HWIF_BINIT_RLIST_F10             */ {/*swreg*/ 45,  5, 10,  1},
/* HWIF_BINIT_RLIST_B9              */ {/*swreg*/ 45,  5,  5,  1},
/* HWIF_BINIT_RLIST_F9              */ {/*swreg*/ 45,  5,  0,  1},
/* HWIF_PRED_BC_TAP_7_2             */ {/*swreg*/ 45, 10, 22,  1},
/* HWIF_PRED_BC_TAP_7_3             */ {/*swreg*/ 45, 10, 12,  1},
/* HWIF_PRED_TAP_2_M1               */ {/*swreg*/ 45,  2, 10,  1},
/* HWIF_PRED_TAP_2_4                */ {/*swreg*/ 45,  2,  8,  1},
/* HWIF_PRED_TAP_4_M1               */ {/*swreg*/ 45,  2,  6,  1},
/* HWIF_PRED_TAP_4_4                */ {/*swreg*/ 45,  2,  4,  1},
/* HWIF_PRED_TAP_6_M1               */ {/*swreg*/ 45,  2,  2,  1},
/* HWIF_PRED_TAP_6_4                */ {/*swreg*/ 45,  2,  0,  1},
/* HWIF_BINIT_RLIST_B14             */ {/*swreg*/ 46,  5, 25,  1},
/* HWIF_BINIT_RLIST_F14             */ {/*swreg*/ 46,  5, 20,  1},
/* HWIF_BINIT_RLIST_B13             */ {/*swreg*/ 46,  5, 15,  1},
/* HWIF_BINIT_RLIST_F13             */ {/*swreg*/ 46,  5, 10,  1},
/* HWIF_BINIT_RLIST_B12             */ {/*swreg*/ 46,  5,  5,  1},
/* HWIF_BINIT_RLIST_F12             */ {/*swreg*/ 46,  5,  0,  1},
/* HWIF_QUANT_DELTA_2               */ {/*swreg*/ 46,  5, 27,  1},
/* HWIF_QUANT_DELTA_3               */ {/*swreg*/ 46,  5, 22,  1},
/* HWIF_QUANT_2                     */ {/*swreg*/ 46, 11, 11,  1},
/* HWIF_QUANT_3                     */ {/*swreg*/ 46, 11,  0,  1},
/* HWIF_CUR_POC_00                  */ {/*swreg*/ 46,  8, 24,  1},
/* HWIF_CUR_POC_01                  */ {/*swreg*/ 46,  8, 16,  1},
/* HWIF_CUR_POC_02                  */ {/*swreg*/ 46,  8,  8,  1},
/* HWIF_CUR_POC_03                  */ {/*swreg*/ 46,  8,  0,  1},
/* HWIF_PINIT_RLIST_F3              */ {/*swreg*/ 47,  5, 25,  1},
/* HWIF_PINIT_RLIST_F2              */ {/*swreg*/ 47,  5, 20,  1},
/* HWIF_PINIT_RLIST_F1              */ {/*swreg*/ 47,  5, 15,  1},
/* HWIF_PINIT_RLIST_F0              */ {/*swreg*/ 47,  5, 10,  1},
/* HWIF_BINIT_RLIST_B15             */ {/*swreg*/ 47,  5,  5,  1},
/* HWIF_BINIT_RLIST_F15             */ {/*swreg*/ 47,  5,  0,  1},
/* HWIF_QUANT_DELTA_4               */ {/*swreg*/ 47,  5, 27,  1},
/* HWIF_QUANT_4                     */ {/*swreg*/ 47, 11, 11,  1},
/* HWIF_QUANT_5                     */ {/*swreg*/ 47, 11,  0,  1},
/* HWIF_CUR_POC_04                  */ {/*swreg*/ 47,  8, 24,  1},
/* HWIF_CUR_POC_05                  */ {/*swreg*/ 47,  8, 16,  1},
/* HWIF_CUR_POC_06                  */ {/*swreg*/ 47,  8,  8,  1},
/* HWIF_CUR_POC_07                  */ {/*swreg*/ 47,  8,  0,  1},
/* HWIF_STARTMB_X                   */ {/*swreg*/ 48,  9, 23,  1},
/* HWIF_STARTMB_Y                   */ {/*swreg*/ 48,  9, 14,  1},
/* HWIF_ERROR_CONC_MODE             */ {/*swreg*/ 48,  2, 12,  1},
/* HWIF_CUR_POC_08                  */ {/*swreg*/ 48,  8, 24,  1},
/* HWIF_CUR_POC_09                  */ {/*swreg*/ 48,  8, 16,  1},
/* HWIF_CUR_POC_10                  */ {/*swreg*/ 48,  8,  8,  1},
/* HWIF_CUR_POC_11                  */ {/*swreg*/ 48,  8,  0,  1},
/* HWIF_PRED_BC_TAP_0_0             */ {/*swreg*/ 49, 10, 22,  1},
/* HWIF_PRED_BC_TAP_0_1             */ {/*swreg*/ 49, 10, 12,  1},
/* HWIF_PRED_BC_TAP_0_2             */ {/*swreg*/ 49, 10,  2,  1},
/* HWIF_CUR_POC_12                  */ {/*swreg*/ 49,  8, 24,  1},
/* HWIF_CUR_POC_13                  */ {/*swreg*/ 49,  8, 16,  1},
/* HWIF_CUR_POC_14                  */ {/*swreg*/ 49,  8,  8,  1},
/* HWIF_CUR_POC_15                  */ {/*swreg*/ 49,  8,  0,  1},
/* HWIF_APF_DISABLE                 */ {/*swreg*/ 55,  1, 31,  1},
/* HWIF_APF_SINGLE_PU_MODE          */ {/*swreg*/ 55,  1, 30,  1},
/* HWIF_APF_THRESHOLD               */ {/*swreg*/ 55, 16,  0,  1},
/* HWIF_SERV_MERGE_DIS              */ {/*swreg*/ 58,  1, 31,  1},
/* HWIF_DEC_MULTICORE_E             */ {/*swreg*/ 58,  1, 30,  1},
/* HWIF_DEC_WRITESTAT_E             */ {/*swreg*/ 58,  1, 29,  1},
/* HWIF_DEC_MC_POLLMODE             */ {/*swreg*/ 58,  2, 27,  1},
/* HWIF_DEC_MC_POLLTIME             */ {/*swreg*/ 58, 10, 17,  1},
/* HWIF_DEC_REFER_DOUBLEBUFFER_E    */ {/*swreg*/ 58,  1, 15,  1},
/* HWIF_DEC_AXI_RD_ID_E             */ {/*swreg*/ 58,  1, 14,  1},
/* HWIF_DEC_AXI_WD_ID_E             */ {/*swreg*/ 58,  1, 13,  1},
/* HWIF_DEC_BUSWIDTH                */ {/*swreg*/ 58,  3,  8,  1},
/* HWIF_DEC_MAX_BURST               */ {/*swreg*/ 58,  8,  0,  1},
/* HWIF_GREF_SIGN_BIAS              */ {/*swreg*/ 59,  1, 29,  1},
/* HWIF_AREF_SIGN_BIAS              */ {/*swreg*/ 59,  1, 28,  1},
/* HWIF_FILT_REF_ADJ_0              */ {/*swreg*/ 59,  7, 21,  1},
/* HWIF_FILT_REF_ADJ_1              */ {/*swreg*/ 59,  7, 14,  1},
/* HWIF_FILT_REF_ADJ_2              */ {/*swreg*/ 59,  7,  7,  1},
/* HWIF_FILT_REF_ADJ_3              */ {/*swreg*/ 59,  7,  0,  1},
/* HWIF_DEC_AXI_WR_ID               */ {/*swreg*/ 60, 16, 16,  1},
/* HWIF_DEC_AXI_RD_ID               */ {/*swreg*/ 60, 16,  0,  1},
/* HWIF_MB_LOCATION_X               */ {/*swreg*/ 62, 16, 16,  0},
/* HWIF_MB_LOCATION_Y               */ {/*swreg*/ 62, 16,  0,  0},
/* HWIF_CU_LOCATION_X               */ {/*swreg*/ 62, 16, 16,  0},
/* HWIF_CU_LOCATION_Y               */ {/*swreg*/ 62, 16,  0,  0},
/* HWIF_PERF_CYCLE_COUNT            */ {/*swreg*/ 63, 32,  0,  0},
/* HWIF_DEC_OUT_YBASE_MSB           */ {/*swreg*/ 64, 32,  0,  1},
/* HWIF_DEC_OUT_BASE_MSB            */ {/*swreg*/ 64, 32,  0,  1},
/* HWIF_DEC_OUT_YBASE_LSB           */ {/*swreg*/ 65, 32,  0,  1},
/* HWIF_DEC_OUT_BASE_LSB            */ {/*swreg*/ 65, 32,  0,  1},
/* HWIF_DPB_ILACE_MODE              */ {/*swreg*/ 65,  1,  1,  1},
/* HWIF_REFER0_YBASE_MSB            */ {/*swreg*/ 66, 32,  0,  1},
/* HWIF_REFER0_BASE_MSB             */ {/*swreg*/ 66, 32,  0,  1},
/* HWIF_JPG_CH_OUT_BASE_MSB         */ {/*swreg*/ 66, 32,  0,  1},
/* HWIF_REFER0_YBASE_LSB            */ {/*swreg*/ 67, 32,  0,  1},
/* HWIF_REFER0_BASE_LSB             */ {/*swreg*/ 67, 32,  0,  1},
/* HWIF_REFER0_FIELD_E              */ {/*swreg*/ 67,  1,  1,  1},
/* HWIF_REFER0_TOPC_E               */ {/*swreg*/ 67,  1,  0,  1},
/* HWIF_JPG_CH_OUT_BASE_LSB         */ {/*swreg*/ 67, 32,  0,  1},
/* HWIF_REFER1_YBASE_MSB            */ {/*swreg*/ 68, 32,  0,  1},
/* HWIF_REFER1_BASE_MSB             */ {/*swreg*/ 68, 32,  0,  1},
/* HWIF_REFER1_YBASE_LSB            */ {/*swreg*/ 69, 32,  0,  1},
/* HWIF_REFER1_BASE_LSB             */ {/*swreg*/ 69, 32,  0,  1},
/* HWIF_REFER1_FIELD_E              */ {/*swreg*/ 69,  1,  1,  1},
/* HWIF_REFER1_TOPC_E               */ {/*swreg*/ 69,  1,  0,  1},
/* HWIF_REFER2_YBASE_MSB            */ {/*swreg*/ 70, 32,  0,  1},
/* HWIF_REFER2_BASE_MSB             */ {/*swreg*/ 70, 32,  0,  1},
/* HWIF_REFER2_YBASE_LSB            */ {/*swreg*/ 71, 32,  0,  1},
/* HWIF_REFER2_BASE_LSB             */ {/*swreg*/ 71, 32,  0,  1},
/* HWIF_REFER2_FIELD_E              */ {/*swreg*/ 71,  1,  1,  1},
/* HWIF_REFER2_TOPC_E               */ {/*swreg*/ 71,  1,  0,  1},
/* HWIF_REFER3_YBASE_MSB            */ {/*swreg*/ 72, 32,  0,  1},
/* HWIF_REFER3_BASE_MSB             */ {/*swreg*/ 72, 32,  0,  1},
/* HWIF_REFER3_YBASE_LSB            */ {/*swreg*/ 73, 32,  0,  1},
/* HWIF_REFER3_BASE_LSB             */ {/*swreg*/ 73, 32,  0,  1},
/* HWIF_REFER3_FIELD_E              */ {/*swreg*/ 73,  1,  1,  1},
/* HWIF_REFER3_TOPC_E               */ {/*swreg*/ 73,  1,  0,  1},
/* HWIF_REFER4_YBASE_MSB            */ {/*swreg*/ 74, 32,  0,  1},
/* HWIF_REFER4_BASE_MSB             */ {/*swreg*/ 74, 32,  0,  1},
/* HWIF_REFER4_YBASE_LSB            */ {/*swreg*/ 75, 32,  0,  1},
/* HWIF_REFER4_BASE_LSB             */ {/*swreg*/ 75, 32,  0,  1},
/* HWIF_REFER4_FIELD_E              */ {/*swreg*/ 75,  1,  1,  1},
/* HWIF_REFER4_TOPC_E               */ {/*swreg*/ 75,  1,  0,  1},
/* HWIF_REFER5_YBASE_MSB            */ {/*swreg*/ 76, 32,  0,  1},
/* HWIF_REFER5_BASE_MSB             */ {/*swreg*/ 76, 32,  0,  1},
/* HWIF_REFER5_YBASE_LSB            */ {/*swreg*/ 77, 32,  0,  1},
/* HWIF_REFER5_BASE_LSB             */ {/*swreg*/ 77, 32,  0,  1},
/* HWIF_REFER5_FIELD_E              */ {/*swreg*/ 77,  1,  1,  1},
/* HWIF_REFER5_TOPC_E               */ {/*swreg*/ 77,  1,  0,  1},
/* HWIF_REFER6_YBASE_MSB            */ {/*swreg*/ 78, 32,  0,  1},
/* HWIF_SEGMENT_WRITE_BASE_MSB      */ {/*swreg*/ 78, 32,  0,  1},
/* HWIF_REFER6_BASE_MSB             */ {/*swreg*/ 78, 32,  0,  1},
/* HWIF_VP8_DEC_CH_BASE_MSB         */ {/*swreg*/ 78, 32,  0,  1},
/* HWIF_REFER6_YBASE_LSB            */ {/*swreg*/ 79, 32,  0,  1},
/* HWIF_SEGMENT_WRITE_BASE_LSB      */ {/*swreg*/ 79, 32,  0,  1},
/* HWIF_REFER6_BASE_LSB             */ {/*swreg*/ 79, 32,  0,  1},
/* HWIF_REFER6_FIELD_E              */ {/*swreg*/ 79,  1,  1,  1},
/* HWIF_REFER6_TOPC_E               */ {/*swreg*/ 79,  1,  0,  1},
/* HWIF_VP8_DEC_CH_BASE_LSB         */ {/*swreg*/ 79, 32,  0,  1},
/* HWIF_VP8_STRIDE_E                */ {/*swreg*/ 79,  1,  1,  1},
/* HWIF_VP8_CH_BASE_E               */ {/*swreg*/ 79,  1,  0,  1},
/* HWIF_REFER7_YBASE_MSB            */ {/*swreg*/ 80, 32,  0,  1},
/* HWIF_SEGMENT_READ_BASE_MSB       */ {/*swreg*/ 80, 32,  0,  1},
/* HWIF_REFER7_BASE_MSB             */ {/*swreg*/ 80, 32,  0,  1},
/* HWIF_REFER7_YBASE_LSB            */ {/*swreg*/ 81, 32,  0,  1},
/* HWIF_SEGMENT_READ_BASE_LSB       */ {/*swreg*/ 81, 32,  0,  1},
/* HWIF_REFER7_BASE_LSB             */ {/*swreg*/ 81, 32,  0,  1},
/* HWIF_REFER7_FIELD_E              */ {/*swreg*/ 81,  1,  1,  1},
/* HWIF_REFER7_TOPC_E               */ {/*swreg*/ 81,  1,  0,  1},
/* HWIF_REFER8_YBASE_MSB            */ {/*swreg*/ 82, 32,  0,  1},
/* HWIF_REFER8_BASE_MSB             */ {/*swreg*/ 82, 32,  0,  1},
/* HWIF_DCT_STRM1_BASE_MSB          */ {/*swreg*/ 82, 32,  0,  1},
/* HWIF_REFER8_YBASE_LSB            */ {/*swreg*/ 83, 32,  0,  1},
/* HWIF_REFER8_BASE_LSB             */ {/*swreg*/ 83, 32,  0,  1},
/* HWIF_DCT_STRM1_BASE_LSB          */ {/*swreg*/ 83, 32,  0,  1},
/* HWIF_REFER8_FIELD_E              */ {/*swreg*/ 83,  1,  1,  1},
/* HWIF_REFER8_TOPC_E               */ {/*swreg*/ 83,  1,  0,  1},
/* HWIF_REFER9_YBASE_MSB            */ {/*swreg*/ 84, 32,  0,  1},
/* HWIF_REFER9_BASE_MSB             */ {/*swreg*/ 84, 32,  0,  1},
/* HWIF_DCT_STRM2_BASE_MSB          */ {/*swreg*/ 84, 32,  0,  1},
/* HWIF_REFER9_YBASE_LSB            */ {/*swreg*/ 85, 32,  0,  1},
/* HWIF_REFER9_BASE_LSB             */ {/*swreg*/ 85, 32,  0,  1},
/* HWIF_DCT_STRM2_BASE_LSB          */ {/*swreg*/ 85, 32,  0,  1},
/* HWIF_REFER9_FIELD_E              */ {/*swreg*/ 85,  1,  1,  1},
/* HWIF_REFER9_TOPC_E               */ {/*swreg*/ 85,  1,  0,  1},
/* HWIF_REFER10_YBASE_MSB           */ {/*swreg*/ 86, 32,  0,  1},
/* HWIF_REFER10_BASE_MSB            */ {/*swreg*/ 86, 32,  0,  1},
/* HWIF_DCT_STRM3_BASE_MSB          */ {/*swreg*/ 86, 32,  0,  1},
/* HWIF_REFER10_YBASE_LSB           */ {/*swreg*/ 87, 32,  0,  1},
/* HWIF_REFER10_BASE_LSB            */ {/*swreg*/ 87, 32,  0,  1},
/* HWIF_DCT_STRM3_BASE_LSB          */ {/*swreg*/ 87, 32,  0,  1},
/* HWIF_REFER10_FIELD_E             */ {/*swreg*/ 87,  1,  1,  1},
/* HWIF_REFER10_TOPC_E              */ {/*swreg*/ 87,  1,  0,  1},
/* HWIF_REFER11_YBASE_MSB           */ {/*swreg*/ 88, 32,  0,  1},
/* HWIF_REFER11_BASE_MSB            */ {/*swreg*/ 88, 32,  0,  1},
/* HWIF_DCT_STRM4_BASE_MSB          */ {/*swreg*/ 88, 32,  0,  1},
/* HWIF_REFER11_YBASE_LSB           */ {/*swreg*/ 89, 32,  0,  1},
/* HWIF_REFER11_BASE_LSB            */ {/*swreg*/ 89, 32,  0,  1},
/* HWIF_DCT_STRM4_BASE_LSB          */ {/*swreg*/ 89, 32,  0,  1},
/* HWIF_REFER11_FIELD_E             */ {/*swreg*/ 89,  1,  1,  1},
/* HWIF_REFER11_TOPC_E              */ {/*swreg*/ 89,  1,  0,  1},
/* HWIF_REFER12_YBASE_MSB           */ {/*swreg*/ 90, 32,  0,  1},
/* HWIF_REFER12_BASE_MSB            */ {/*swreg*/ 90, 32,  0,  1},
/* HWIF_DCT_STRM5_BASE_MSB          */ {/*swreg*/ 90, 32,  0,  1},
/* HWIF_REFER12_YBASE_LSB           */ {/*swreg*/ 91, 32,  0,  1},
/* HWIF_REFER12_BASE_LSB            */ {/*swreg*/ 91, 32,  0,  1},
/* HWIF_DCT_STRM5_BASE_LSB          */ {/*swreg*/ 91, 32,  0,  1},
/* HWIF_REFER12_FIELD_E             */ {/*swreg*/ 91,  1,  1,  1},
/* HWIF_REFER12_TOPC_E              */ {/*swreg*/ 91,  1,  0,  1},
/* HWIF_REFER13_YBASE_MSB           */ {/*swreg*/ 92, 32,  0,  1},
/* HWIF_REFER13_BASE_MSB            */ {/*swreg*/ 92, 32,  0,  1},
/* HWIF_BITPL_CTRL_BASE_MSB         */ {/*swreg*/ 92, 32,  0,  1},
/* HWIF_REFER13_YBASE_LSB           */ {/*swreg*/ 93, 32,  0,  1},
/* HWIF_REFER13_BASE_LSB            */ {/*swreg*/ 93, 32,  0,  1},
/* HWIF_REFER13_FIELD_E             */ {/*swreg*/ 93,  1,  1,  1},
/* HWIF_REFER13_TOPC_E              */ {/*swreg*/ 93,  1,  0,  1},
/* HWIF_BITPL_CTRL_BASE_LSB         */ {/*swreg*/ 93, 32,  0,  1},
/* HWIF_REFER14_YBASE_MSB           */ {/*swreg*/ 94, 32,  0,  1},
/* HWIF_REFER14_BASE_MSB            */ {/*swreg*/ 94, 32,  0,  1},
/* HWIF_DCT_STRM6_BASE_MSB          */ {/*swreg*/ 94, 32,  0,  1},
/* HWIF_REFER14_YBASE_LSB           */ {/*swreg*/ 95, 32,  0,  1},
/* HWIF_REFER14_BASE_LSB            */ {/*swreg*/ 95, 32,  0,  1},
/* HWIF_DCT_STRM6_BASE_LSB          */ {/*swreg*/ 95, 32,  0,  1},
/* HWIF_REFER14_FIELD_E             */ {/*swreg*/ 95,  1,  1,  1},
/* HWIF_REFER14_TOPC_E              */ {/*swreg*/ 95,  1,  0,  1},
/* HWIF_REFER15_YBASE_MSB           */ {/*swreg*/ 96, 32,  0,  1},
/* HWIF_REFER15_BASE_MSB            */ {/*swreg*/ 96, 32,  0,  1},
/* HWIF_DCT_STRM7_BASE_MSB          */ {/*swreg*/ 96, 32,  0,  1},
/* HWIF_REFER15_YBASE_LSB           */ {/*swreg*/ 97, 32,  0,  1},
/* HWIF_REFER15_BASE_LSB            */ {/*swreg*/ 97, 32,  0,  1},
/* HWIF_DCT_STRM7_BASE_LSB          */ {/*swreg*/ 97, 32,  0,  1},
/* HWIF_REFER15_FIELD_E             */ {/*swreg*/ 97,  1,  1,  1},
/* HWIF_REFER15_TOPC_E              */ {/*swreg*/ 97,  1,  0,  1},
/* HWIF_DEC_OUT_CBASE_MSB           */ {/*swreg*/ 98, 32,  0,  1},
/* HWIF_DEC_OUT_CBASE_LSB           */ {/*swreg*/ 99, 32,  0,  1},
/* HWIF_REFER0_CBASE_MSB            */ {/*swreg*/100, 32,  0,  1},
/* HWIF_REFER0_CBASE_LSB            */ {/*swreg*/101, 32,  0,  1},
/* HWIF_REFER1_CBASE_MSB            */ {/*swreg*/102, 32,  0,  1},
/* HWIF_REFER1_CBASE_LSB            */ {/*swreg*/103, 32,  0,  1},
/* HWIF_REFER2_CBASE_MSB            */ {/*swreg*/104, 32,  0,  1},
/* HWIF_REFER2_CBASE_LSB            */ {/*swreg*/105, 32,  0,  1},
/* HWIF_REFER3_CBASE_MSB            */ {/*swreg*/106, 32,  0,  1},
/* HWIF_REFER3_CBASE_LSB            */ {/*swreg*/107, 32,  0,  1},
/* HWIF_REFER4_CBASE_MSB            */ {/*swreg*/108, 32,  0,  1},
/* HWIF_REFER4_CBASE_LSB            */ {/*swreg*/109, 32,  0,  1},
/* HWIF_REFER5_CBASE_MSB            */ {/*swreg*/110, 32,  0,  1},
/* HWIF_REFER5_CBASE_LSB            */ {/*swreg*/111, 32,  0,  1},
/* HWIF_REFER6_CBASE_MSB            */ {/*swreg*/112, 32,  0,  1},
/* HWIF_REFER6_CBASE_LSB            */ {/*swreg*/113, 32,  0,  1},
/* HWIF_REFER7_CBASE_MSB            */ {/*swreg*/114, 32,  0,  1},
/* HWIF_REFER7_CBASE_LSB            */ {/*swreg*/115, 32,  0,  1},
/* HWIF_REFER8_CBASE_MSB            */ {/*swreg*/116, 32,  0,  1},
/* HWIF_REFER8_CBASE_LSB            */ {/*swreg*/117, 32,  0,  1},
/* HWIF_REFER9_CBASE_MSB            */ {/*swreg*/118, 32,  0,  1},
/* HWIF_REFER9_CBASE_LSB            */ {/*swreg*/119, 32,  0,  1},
/* HWIF_REFER10_CBASE_MSB           */ {/*swreg*/120, 32,  0,  1},
/* HWIF_REFER10_CBASE_LSB           */ {/*swreg*/121, 32,  0,  1},
/* HWIF_REFER11_CBASE_MSB           */ {/*swreg*/122, 32,  0,  1},
/* HWIF_REFER11_CBASE_LSB           */ {/*swreg*/123, 32,  0,  1},
/* HWIF_REFER12_CBASE_MSB           */ {/*swreg*/124, 32,  0,  1},
/* HWIF_REFER12_CBASE_LSB           */ {/*swreg*/125, 32,  0,  1},
/* HWIF_REFER13_CBASE_MSB           */ {/*swreg*/126, 32,  0,  1},
/* HWIF_REFER13_CBASE_LSB           */ {/*swreg*/127, 32,  0,  1},
/* HWIF_REFER14_CBASE_MSB           */ {/*swreg*/128, 32,  0,  1},
/* HWIF_REFER14_CBASE_LSB           */ {/*swreg*/129, 32,  0,  1},
/* HWIF_REFER15_CBASE_MSB           */ {/*swreg*/130, 32,  0,  1},
/* HWIF_REFER15_CBASE_LSB           */ {/*swreg*/131, 32,  0,  1},
/* HWIF_DEC_OUT_DBASE_MSB           */ {/*swreg*/132, 32,  0,  1},
/* HWIF_DIR_MV_BASE_MSB             */ {/*swreg*/132, 32,  0,  1},
/* HWIF_DEC_OUT_DBASE_LSB           */ {/*swreg*/133, 32,  0,  1},
/* HWIF_DIR_MV_BASE_LSB             */ {/*swreg*/133, 32,  0,  1},
/* HWIF_REFER0_DBASE_MSB            */ {/*swreg*/134, 32,  0,  1},
/* HWIF_REFER0_DBASE_LSB            */ {/*swreg*/135, 32,  0,  1},
/* HWIF_REFER1_DBASE_MSB            */ {/*swreg*/136, 32,  0,  1},
/* HWIF_REFER1_DBASE_LSB            */ {/*swreg*/137, 32,  0,  1},
/* HWIF_REFER2_DBASE_MSB            */ {/*swreg*/138, 32,  0,  1},
/* HWIF_REFER2_DBASE_LSB            */ {/*swreg*/139, 32,  0,  1},
/* HWIF_REFER3_DBASE_MSB            */ {/*swreg*/140, 32,  0,  1},
/* HWIF_REFER3_DBASE_LSB            */ {/*swreg*/141, 32,  0,  1},
/* HWIF_REFER4_DBASE_MSB            */ {/*swreg*/142, 32,  0,  1},
/* HWIF_REFER4_DBASE_LSB            */ {/*swreg*/143, 32,  0,  1},
/* HWIF_REFER5_DBASE_MSB            */ {/*swreg*/144, 32,  0,  1},
/* HWIF_REFER5_DBASE_LSB            */ {/*swreg*/145, 32,  0,  1},
/* HWIF_REFER6_DBASE_MSB            */ {/*swreg*/146, 32,  0,  1},
/* HWIF_REFER6_DBASE_LSB            */ {/*swreg*/147, 32,  0,  1},
/* HWIF_REFER7_DBASE_MSB            */ {/*swreg*/148, 32,  0,  1},
/* HWIF_REFER7_DBASE_LSB            */ {/*swreg*/149, 32,  0,  1},
/* HWIF_REFER8_DBASE_MSB            */ {/*swreg*/150, 32,  0,  1},
/* HWIF_REFER8_DBASE_LSB            */ {/*swreg*/151, 32,  0,  1},
/* HWIF_REFER9_DBASE_MSB            */ {/*swreg*/152, 32,  0,  1},
/* HWIF_REFER9_DBASE_LSB            */ {/*swreg*/153, 32,  0,  1},
/* HWIF_REFER10_DBASE_MSB           */ {/*swreg*/154, 32,  0,  1},
/* HWIF_REFER10_DBASE_LSB           */ {/*swreg*/155, 32,  0,  1},
/* HWIF_REFER11_DBASE_MSB           */ {/*swreg*/156, 32,  0,  1},
/* HWIF_REFER11_DBASE_LSB           */ {/*swreg*/157, 32,  0,  1},
/* HWIF_REFER12_DBASE_MSB           */ {/*swreg*/158, 32,  0,  1},
/* HWIF_REFER12_DBASE_LSB           */ {/*swreg*/159, 32,  0,  1},
/* HWIF_REFER13_DBASE_MSB           */ {/*swreg*/160, 32,  0,  1},
/* HWIF_REFER13_DBASE_LSB           */ {/*swreg*/161, 32,  0,  1},
/* HWIF_REFER14_DBASE_MSB           */ {/*swreg*/162, 32,  0,  1},
/* HWIF_REFER14_DBASE_LSB           */ {/*swreg*/163, 32,  0,  1},
/* HWIF_REFER15_DBASE_MSB           */ {/*swreg*/164, 32,  0,  1},
/* HWIF_REFER15_DBASE_LSB           */ {/*swreg*/165, 32,  0,  1},
/* HWIF_TILE_BASE_MSB               */ {/*swreg*/166, 32,  0,  1},
/* HWIF_TILE_BASE_LSB               */ {/*swreg*/167, 32,  0,  1},
/* HWIF_STREAM_BASE_MSB             */ {/*swreg*/168, 32,  0,  1},
/* HWIF_RLC_VLC_BASE_MSB            */ {/*swreg*/168, 32,  0,  1},
/* HWIF_STREAM_BASE_LSB             */ {/*swreg*/169, 32,  0,  1},
/* HWIF_RLC_VLC_BASE_LSB            */ {/*swreg*/169, 32,  0,  1},
/* HWIF_SCALE_LIST_BASE_MSB         */ {/*swreg*/170, 32,  0,  1},
/* HWIF_CTX_COUNTER_BASE_MSB        */ {/*swreg*/170, 32,  0,  1},
/* HWIF_MB_CTRL_BASE_MSB            */ {/*swreg*/170, 32,  0,  1},
/* HWIF_SCALE_LIST_BASE_LSB         */ {/*swreg*/171, 32,  0,  1},
/* HWIF_CTX_COUNTER_BASE_LSB        */ {/*swreg*/171, 32,  0,  1},
/* HWIF_MB_CTRL_BASE_LSB            */ {/*swreg*/171, 32,  0,  1},
/* HWIF_PROB_TAB_BASE_MSB           */ {/*swreg*/172, 32,  0,  1},
/* HWIF_DIFF_MV_BASE_MSB            */ {/*swreg*/172, 32,  0,  1},
/* HWIF_SEGMENT_BASE_MSB            */ {/*swreg*/172, 32,  0,  1},
/* HWIF_PROB_TAB_BASE_LSB           */ {/*swreg*/173, 32,  0,  1},
/* HWIF_DIFF_MV_BASE_LSB            */ {/*swreg*/173, 32,  0,  1},
/* HWIF_SEGMENT_BASE_LSB            */ {/*swreg*/173, 32,  0,  1},
/* HWIF_QTABLE_BASE_MSB             */ {/*swreg*/174, 32,  0,  1},
/* HWIF_QTABLE_BASE_LSB             */ {/*swreg*/175, 32,  0,  1},
/* HWIF_I4X4_OR_DC_BASE_MSB         */ {/*swreg*/176, 32,  0,  1},
/* HWIF_PJPEG_DCCB_BASE_MSB         */ {/*swreg*/176, 32,  0,  1},
/* HWIF_I4X4_OR_DC_BASE_LSB         */ {/*swreg*/177, 32,  0,  1},
/* HWIF_PJPEG_DCCB_BASE_LSB         */ {/*swreg*/177, 32,  0,  1},
/* HWIF_DEC_VERT_FILT_BASE_MSB      */ {/*swreg*/178, 32,  0,  1},
/* HWIF_PJPEG_DCCR_BASE_MSB         */ {/*swreg*/178, 32,  0,  1},
/* HWIF_DEC_VERT_FILT_BASE_LSB      */ {/*swreg*/179, 32,  0,  1},
/* HWIF_PJPEG_DCCR_BASE_LSB         */ {/*swreg*/179, 32,  0,  1},
/* HWIF_DEC_VERT_SAO_BASE_MSB       */ {/*swreg*/180, 32,  0,  1},
/* HWIF_DIR_MV_BASE2_MSB            */ {/*swreg*/180, 32,  0,  1},
/* HWIF_DEC_VERT_SAO_BASE_LSB       */ {/*swreg*/181, 32,  0,  1},
/* HWIF_DIR_MV_BASE2_LSB            */ {/*swreg*/181, 32,  0,  1},
/* HWIF_DEC_BSD_CTRL_BASE_MSB       */ {/*swreg*/182, 32,  0,  1},
/* HWIF_DEC_CH8PIX_BASE_MSB         */ {/*swreg*/182, 32,  0,  1},
/* HWIF_DEC_BSD_CTRL_BASE_LSB       */ {/*swreg*/183, 32,  0,  1},
/* HWIF_DEC_CH8PIX_BASE_LSB         */ {/*swreg*/183, 32,  0,  1},
/* HWIF_DEC_OUT_TYBASE_MSB          */ {/*swreg*/189, 32,  0,  1},
/* HWIF_DEC_OUT_TYBASE_LSB          */ {/*swreg*/190, 32,  0,  1},
/* HWIF_REFER0_TYBASE_MSB           */ {/*swreg*/191, 32,  0,  1},
/* HWIF_REFER0_TYBASE_LSB           */ {/*swreg*/192, 32,  0,  1},
/* HWIF_REFER1_TYBASE_MSB           */ {/*swreg*/193, 32,  0,  1},
/* HWIF_REFER1_TYBASE_LSB           */ {/*swreg*/194, 32,  0,  1},
/* HWIF_REFER2_TYBASE_MSB           */ {/*swreg*/195, 32,  0,  1},
/* HWIF_REFER2_TYBASE_LSB           */ {/*swreg*/196, 32,  0,  1},
/* HWIF_REFER3_TYBASE_MSB           */ {/*swreg*/197, 32,  0,  1},
/* HWIF_REFER3_TYBASE_LSB           */ {/*swreg*/198, 32,  0,  1},
/* HWIF_REFER4_TYBASE_MSB           */ {/*swreg*/199, 32,  0,  1},
/* HWIF_REFER4_TYBASE_LSB           */ {/*swreg*/200, 32,  0,  1},
/* HWIF_REFER5_TYBASE_MSB           */ {/*swreg*/201, 32,  0,  1},
/* HWIF_REFER5_TYBASE_LSB           */ {/*swreg*/202, 32,  0,  1},
/* HWIF_REFER6_TYBASE_MSB           */ {/*swreg*/203, 32,  0,  1},
/* HWIF_REFER6_TYBASE_LSB           */ {/*swreg*/204, 32,  0,  1},
/* HWIF_REFER7_TYBASE_MSB           */ {/*swreg*/205, 32,  0,  1},
/* HWIF_REFER7_TYBASE_LSB           */ {/*swreg*/206, 32,  0,  1},
/* HWIF_REFER8_TYBASE_MSB           */ {/*swreg*/207, 32,  0,  1},
/* HWIF_REFER8_TYBASE_LSB           */ {/*swreg*/208, 32,  0,  1},
/* HWIF_REFER9_TYBASE_MSB           */ {/*swreg*/209, 32,  0,  1},
/* HWIF_REFER9_TYBASE_LSB           */ {/*swreg*/210, 32,  0,  1},
/* HWIF_REFER10_TYBASE_MSB          */ {/*swreg*/211, 32,  0,  1},
/* HWIF_REFER10_TYBASE_LSB          */ {/*swreg*/212, 32,  0,  1},
/* HWIF_REFER11_TYBASE_MSB          */ {/*swreg*/213, 32,  0,  1},
/* HWIF_REFER11_TYBASE_LSB          */ {/*swreg*/214, 32,  0,  1},
/* HWIF_REFER12_TYBASE_MSB          */ {/*swreg*/215, 32,  0,  1},
/* HWIF_REFER12_TYBASE_LSB          */ {/*swreg*/216, 32,  0,  1},
/* HWIF_REFER13_TYBASE_MSB          */ {/*swreg*/217, 32,  0,  1},
/* HWIF_REFER13_TYBASE_LSB          */ {/*swreg*/218, 32,  0,  1},
/* HWIF_REFER14_TYBASE_MSB          */ {/*swreg*/219, 32,  0,  1},
/* HWIF_REFER14_TYBASE_LSB          */ {/*swreg*/220, 32,  0,  1},
/* HWIF_REFER15_TYBASE_MSB          */ {/*swreg*/221, 32,  0,  1},
/* HWIF_REFER15_TYBASE_LSB          */ {/*swreg*/222, 32,  0,  1},
/* HWIF_DEC_OUT_TCBASE_MSB          */ {/*swreg*/223, 32,  0,  1},
/* HWIF_DEC_OUT_TCBASE_LSB          */ {/*swreg*/224, 32,  0,  1},
/* HWIF_REFER0_TCBASE_MSB           */ {/*swreg*/225, 32,  0,  1},
/* HWIF_REFER0_TCBASE_LSB           */ {/*swreg*/226, 32,  0,  1},
/* HWIF_REFER1_TCBASE_MSB           */ {/*swreg*/227, 32,  0,  1},
/* HWIF_REFER1_TCBASE_LSB           */ {/*swreg*/228, 32,  0,  1},
/* HWIF_REFER2_TCBASE_MSB           */ {/*swreg*/229, 32,  0,  1},
/* HWIF_REFER2_TCBASE_LSB           */ {/*swreg*/230, 32,  0,  1},
/* HWIF_REFER3_TCBASE_MSB           */ {/*swreg*/231, 32,  0,  1},
/* HWIF_REFER3_TCBASE_LSB           */ {/*swreg*/232, 32,  0,  1},
/* HWIF_REFER4_TCBASE_MSB           */ {/*swreg*/233, 32,  0,  1},
/* HWIF_REFER4_TCBASE_LSB           */ {/*swreg*/234, 32,  0,  1},
/* HWIF_REFER5_TCBASE_MSB           */ {/*swreg*/235, 32,  0,  1},
/* HWIF_REFER5_TCBASE_LSB           */ {/*swreg*/236, 32,  0,  1},
/* HWIF_REFER6_TCBASE_MSB           */ {/*swreg*/237, 32,  0,  1},
/* HWIF_REFER6_TCBASE_LSB           */ {/*swreg*/238, 32,  0,  1},
/* HWIF_REFER7_TCBASE_MSB           */ {/*swreg*/239, 32,  0,  1},
/* HWIF_REFER7_TCBASE_LSB           */ {/*swreg*/240, 32,  0,  1},
/* HWIF_REFER8_TCBASE_MSB           */ {/*swreg*/241, 32,  0,  1},
/* HWIF_REFER8_TCBASE_LSB           */ {/*swreg*/242, 32,  0,  1},
/* HWIF_REFER9_TCBASE_MSB           */ {/*swreg*/243, 32,  0,  1},
/* HWIF_REFER9_TCBASE_LSB           */ {/*swreg*/244, 32,  0,  1},
/* HWIF_REFER10_TCBASE_MSB          */ {/*swreg*/245, 32,  0,  1},
/* HWIF_REFER10_TCBASE_LSB          */ {/*swreg*/246, 32,  0,  1},
/* HWIF_REFER11_TCBASE_MSB          */ {/*swreg*/247, 32,  0,  1},
/* HWIF_REFER11_TCBASE_LSB          */ {/*swreg*/248, 32,  0,  1},
/* HWIF_REFER12_TCBASE_MSB          */ {/*swreg*/249, 32,  0,  1},
/* HWIF_REFER12_TCBASE_LSB          */ {/*swreg*/250, 32,  0,  1},
/* HWIF_REFER13_TCBASE_MSB          */ {/*swreg*/251, 32,  0,  1},
/* HWIF_REFER13_TCBASE_LSB          */ {/*swreg*/252, 32,  0,  1},
/* HWIF_REFER14_TCBASE_MSB          */ {/*swreg*/253, 32,  0,  1},
/* HWIF_REFER14_TCBASE_LSB          */ {/*swreg*/254, 32,  0,  1},
/* HWIF_REFER15_TCBASE_MSB          */ {/*swreg*/255, 32,  0,  1},
/* HWIF_REFER15_TCBASE_LSB          */ {/*swreg*/256, 32,  0,  1},
/* HWIF_STRM_BUFFER_LEN             */ {/*swreg*/258, 32,  0,  1},
/* HWIF_STRM_START_OFFSET           */ {/*swreg*/259, 32,  0,  1},
/* HWIF_AXI_WR_4K_DIS               */ {/*swreg*/265,  1, 31,  1},
/* HWIF_IGNORE_SLICE_ERROR_E        */ {/*swreg*/266,  1, 31,  1},
/* HWIF_SKIP8X8                     */ {/*swreg*/267, 24,  7,  0},
/* HWIF_QP_MAX                      */ {/*swreg*/267,  7,  0,  0},
/* HWIF_QP_MIN                      */ {/*swreg*/268,  7, 25,  0},
/* HWIF_QP_COUNT                    */ {/*swreg*/268, 24,  1,  0},
/* HWIF_QP_SUM                      */ {/*swreg*/269, 32,  0,  0},
/* HWIF_FWD_MVX_MAX                 */ {/*swreg*/270, 16, 16,  0},
/* HWIF_FWD_MVX_MIN                 */ {/*swreg*/270, 16,  0,  0},
/* HWIF_FWD_MVY_MAX                 */ {/*swreg*/271, 16, 16,  0},
/* HWIF_FWD_MVY_MIN                 */ {/*swreg*/271, 16,  0,  0},
/* HWIF_MVX_SUM_FWD                 */ {/*swreg*/272, 32,  0,  0},
/* HWIF_MVX_SUM_BWD                 */ {/*swreg*/273, 32,  0,  0},
/* HWIF_MVY_SUM_FWD                 */ {/*swreg*/274, 32,  0,  0},
/* HWIF_MVY_SUM_BWD                 */ {/*swreg*/275, 32,  0,  0},
/* HWIF_PB_INTER_FWD_COUNT          */ {/*swreg*/276, 22,  0,  0},
/* HWIF_PB_INTER_BWD_COUNT          */ {/*swreg*/277, 22,  0,  0},
/* HWIF_PB_INTRA_COUNT              */ {/*swreg*/278, 22,  0,  0},
/* HWIF_BWD_MVX_MAX                 */ {/*swreg*/279, 16, 16,  0},
/* HWIF_BWD_MVX_MIN                 */ {/*swreg*/279, 16,  0,  0},
/* HWIF_BWD_MVY_MAX                 */ {/*swreg*/280, 16, 16,  0},
/* HWIF_BWD_MVY_MIN                 */ {/*swreg*/280, 16,  0,  0},
/* HWIF_SIGNED_MVX_SUM_FWD          */ {/*swreg*/281, 32,  0,  0},
/* HWIF_SIGNED_MVX_SUM_BWD          */ {/*swreg*/282, 32,  0,  0},
/* HWIF_SIGNED_MVY_SUM_FWD          */ {/*swreg*/283, 32,  0,  0},
/* HWIF_SIGNED_MVY_SUM_BWD          */ {/*swreg*/284, 32,  0,  0},
/* HWIF_DEC_OUT_Y_STRIDE            */ {/*swreg*/314, 16, 16,  1},
/* HWIF_DEC_OUT_C_STRIDE            */ {/*swreg*/314, 16,  0,  1},
/* HWIF_STRM_END_OFFSET             */ {/*swreg*/315, 32,  0,  0},
/* HWIF_START_CODE_OFFSET           */ {/*swreg*/316, 32,  0,  0},
/* HWIF_LINE_CNT_INT_E              */ {/*swreg*/317,  1, 31,  1},
/* HWIF_PP_LINE_CNT_SEL             */ {/*swreg*/317,  2, 28,  1},
/* HWIF_LINE_CNT_STRIPE             */ {/*swreg*/317,  8, 16,  1},
/* HWIF_LINE_CNT                    */ {/*swreg*/317, 16,  0,  1},
/* HWIF_EXT_TIMEOUT_OVERRIDE_E      */ {/*swreg*/318,  1, 31,  1},
/* HWIF_EXT_TIMEOUT_CYCLES          */ {/*swreg*/318, 31,  0,  1},
/* HWIF_TIMEOUT_OVERRIDE_E          */ {/*swreg*/319,  1, 31,  1},
/* HWIF_TIMEOUT_CYCLES              */ {/*swreg*/319, 31,  0,  1},
/* HWIF_PP_AXI_RD_ID_U              */ {/*swreg*/320,  8, 24,  1},
/* HWIF_PP_AXI_WR_ID_U              */ {/*swreg*/320,  8, 16,  1},
/* HWIF_PP_IN_BLK_SIZE_U            */ {/*swreg*/320,  3,  8,  1},
/* HWIF_PP_STATUS_U                 */ {/*swreg*/320,  4,  4,  1},
/* HWIF_PP_OUT_TILE_E_U             */ {/*swreg*/320,  1,  3,  1},
/* HWIF_PP_OUT_MODE                 */ {/*swreg*/320,  1,  2,  1},
/* HWIF_PP_CR_FIRST                 */ {/*swreg*/320,  1,  1,  1},
/* HWIF_PP_OUT_E_U                  */ {/*swreg*/320,  1,  0,  1},
/* HWIF_PP_IN_A2_SWAP_U             */ {/*swreg*/321,  4, 28,  1},
/* HWIF_PP_IN_A1_SWAP_U             */ {/*swreg*/321,  4, 24,  1},
/* HWIF_PP_OUT_SWAP_U               */ {/*swreg*/321,  4, 20,  1},
/* HWIF_PP_IN_SWAP_U                */ {/*swreg*/321,  4, 16,  1},
/* HWIF_PP_IN_FORMAT_U              */ {/*swreg*/322,  5, 27,  1},
/* HWIF_HOR_SCALE_MODE_U            */ {/*swreg*/322,  2, 25,  1},
/* HWIF_VER_SCALE_MODE_U            */ {/*swreg*/322,  2, 23,  1},
/* HWIF_PP_OUT_FORMAT_U             */ {/*swreg*/322,  5, 18,  1},
/* HWIF_SCALE_HRATIO_U              */ {/*swreg*/322, 18,  0,  1},
/* HWIF_RANGEMAP_Y_E_U              */ {/*swreg*/323,  1, 31,  1},
/* HWIF_RANGEMAP_C_E_U              */ {/*swreg*/323,  1, 30,  1},
/* HWIF_PP_VC1_ADV_E_U              */ {/*swreg*/323,  1, 28,  1},
/* HWIF_RANGEMAP_COEF_Y_U           */ {/*swreg*/323,  5, 23,  1},
/* HWIF_RANGEMAP_COEF_C_U           */ {/*swreg*/323,  5, 18,  1},
/* HWIF_SCALE_WRATIO_U              */ {/*swreg*/323, 18,  0,  1},
/* HWIF_WSCALE_INVRA_U              */ {/*swreg*/324, 16, 16,  1},
/* HWIF_HSCALE_INVRA_U              */ {/*swreg*/324, 16,  0,  1},
/* HWIF_PP_OUT_LU_BASE_U_MSB        */ {/*swreg*/325, 32,  0,  1},
/* HWIF_PP_OUT_LU_BASE_U_LSB        */ {/*swreg*/326, 32,  0,  1},
/* HWIF_PP_OUT_CH_BASE_U_MSB        */ {/*swreg*/327, 32,  0,  1},
/* HWIF_PP_OUT_CH_BASE_U_LSB        */ {/*swreg*/328, 32,  0,  1},
/* HWIF_PP_OUT_Y_STRIDE             */ {/*swreg*/329, 16, 16,  1},
/* HWIF_PP_OUT_C_STRIDE             */ {/*swreg*/329, 16,  0,  1},
/* HWIF_FLIP_MODE_U                 */ {/*swreg*/330,  2, 29,  1},
/* HWIF_CROP_STARTX_U               */ {/*swreg*/330, 13, 16,  1},
/* HWIF_ROTATION_MODE_U             */ {/*swreg*/330,  2, 13,  1},
/* HWIF_CROP_STARTY_U               */ {/*swreg*/330, 13,  0,  1},
/* HWIF_PP_IN_WIDTH_U               */ {/*swreg*/331, 14, 16,  1},
/* HWIF_PP_IN_HEIGHT_U              */ {/*swreg*/331, 14,  0,  1},
/* HWIF_PP_OUT_WIDTH_U              */ {/*swreg*/332, 16, 16,  1},
/* HWIF_PP_OUT_HEIGHT_U             */ {/*swreg*/332, 16,  0,  1},
/* HWIF_PP_OUT_LU_BOT_BASE_U_MSB    */ {/*swreg*/333, 32,  0,  1},
/* HWIF_PP_OUT_LU_BOT_BASE_U_LSB    */ {/*swreg*/334, 32,  0,  1},
/* HWIF_PP_OUT_CH_BOT_BASE_U_MSB    */ {/*swreg*/335, 32,  0,  1},
/* HWIF_PP_OUT_CH_BOT_BASE_U_LSB    */ {/*swreg*/336, 32,  0,  1},
/* HWIF_PP_IN_Y_STRIDE              */ {/*swreg*/337, 16, 16,  1},
/* HWIF_PP_IN_C_STRIDE              */ {/*swreg*/337, 16,  0,  1},
/* HWIF_PP_IN_LU_BASE_U_MSB         */ {/*swreg*/338, 32,  0,  1},
/* HWIF_PP_IN_LU_BASE_U_LSB         */ {/*swreg*/339, 32,  0,  1},
/* HWIF_PP_IN_CH_BASE_U_MSB         */ {/*swreg*/340, 32,  0,  1},
/* HWIF_PP_IN_CH_BASE_U_LSB         */ {/*swreg*/341, 32,  0,  1},
/* HWIF_PP1_OUT_TILE_E_U            */ {/*swreg*/342,  1,  3,  1},
/* HWIF_PP1_OUT_MODE                */ {/*swreg*/342,  1,  2,  1},
/* HWIF_PP1_CR_FIRST                */ {/*swreg*/342,  1,  1,  1},
/* HWIF_PP1_OUT_E_U                 */ {/*swreg*/342,  1,  0,  1},
/* HWIF_PP1_OUT_SWAP_U              */ {/*swreg*/343,  4, 20,  1},
/* HWIF_PP1_HOR_SCALE_MODE_U        */ {/*swreg*/344,  2, 25,  1},
/* HWIF_PP1_VER_SCALE_MODE_U        */ {/*swreg*/344,  2, 23,  1},
/* HWIF_PP1_OUT_FORMAT_U            */ {/*swreg*/344,  5, 18,  1},
/* HWIF_PP1_SCALE_HRATIO_U          */ {/*swreg*/344, 18,  0,  1},
/* HWIF_PP1_SCALE_WRATIO_U          */ {/*swreg*/345, 18,  0,  1},
/* HWIF_PP1_WSCALE_INVRA_U          */ {/*swreg*/346, 16, 16,  1},
/* HWIF_PP1_HSCALE_INVRA_U          */ {/*swreg*/346, 16,  0,  1},
/* HWIF_PP1_OUT_LU_BASE_U_MSB       */ {/*swreg*/347, 32,  0,  1},
/* HWIF_PP1_OUT_LU_BASE_U_LSB       */ {/*swreg*/348, 32,  0,  1},
/* HWIF_PP1_OUT_CH_BASE_U_MSB       */ {/*swreg*/349, 32,  0,  1},
/* HWIF_PP1_OUT_CH_BASE_U_LSB       */ {/*swreg*/350, 32,  0,  1},
/* HWIF_PP1_OUT_Y_STRIDE            */ {/*swreg*/351, 16, 16,  1},
/* HWIF_PP1_OUT_C_STRIDE            */ {/*swreg*/351, 16,  0,  1},
/* HWIF_PP1_FLIP_MODE_U             */ {/*swreg*/352,  2, 29,  1},
/* HWIF_PP1_CROP_STARTX_U           */ {/*swreg*/352, 13, 16,  1},
/* HWIF_PP1_ROTATION_MODE_U         */ {/*swreg*/352,  2, 13,  1},
/* HWIF_PP1_CROP_STARTY_U           */ {/*swreg*/352, 13,  0,  1},
/* HWIF_PP1_IN_WIDTH_U              */ {/*swreg*/353, 13, 16,  1},
/* HWIF_PP1_IN_HEIGHT_U             */ {/*swreg*/353, 13,  0,  1},
/* HWIF_PP1_OUT_WIDTH_U             */ {/*swreg*/354, 16, 16,  1},
/* HWIF_PP1_OUT_HEIGHT_U            */ {/*swreg*/354, 16,  0,  1},
/* HWIF_PP1_OUT_LU_BOT_BASE_U_MSB   */ {/*swreg*/355, 32,  0,  1},
/* HWIF_PP1_OUT_LU_BOT_BASE_U_LSB   */ {/*swreg*/356, 32,  0,  1},
/* HWIF_PP1_OUT_CH_BOT_BASE_U_MSB   */ {/*swreg*/357, 32,  0,  1},
/* HWIF_PP1_OUT_CH_BOT_BASE_U_LSB   */ {/*swreg*/358, 32,  0,  1},
/* HWIF_PP2_OUT_TILE_E_U            */ {/*swreg*/359,  1,  3,  1},
/* HWIF_PP2_OUT_MODE                */ {/*swreg*/359,  1,  2,  1},
/* HWIF_PP2_CR_FIRST                */ {/*swreg*/359,  1,  1,  1},
/* HWIF_PP2_OUT_E_U                 */ {/*swreg*/359,  1,  0,  1},
/* HWIF_PP2_OUT_SWAP_U              */ {/*swreg*/360,  4, 20,  1},
/* HWIF_PP2_HOR_SCALE_MODE_U        */ {/*swreg*/361,  2, 25,  1},
/* HWIF_PP2_VER_SCALE_MODE_U        */ {/*swreg*/361,  2, 23,  1},
/* HWIF_PP2_OUT_FORMAT_U            */ {/*swreg*/361,  5, 18,  1},
/* HWIF_PP2_SCALE_HRATIO_U          */ {/*swreg*/361, 18,  0,  1},
/* HWIF_PP2_SCALE_WRATIO_U          */ {/*swreg*/362, 18,  0,  1},
/* HWIF_PP2_WSCALE_INVRA_U          */ {/*swreg*/363, 16, 16,  1},
/* HWIF_PP2_HSCALE_INVRA_U          */ {/*swreg*/363, 16,  0,  1},
/* HWIF_PP2_OUT_LU_BASE_U_MSB       */ {/*swreg*/364, 32,  0,  1},
/* HWIF_PP2_OUT_LU_BASE_U_LSB       */ {/*swreg*/365, 32,  0,  1},
/* HWIF_PP2_OUT_CH_BASE_U_MSB       */ {/*swreg*/366, 32,  0,  1},
/* HWIF_PP2_OUT_CH_BASE_U_LSB       */ {/*swreg*/367, 32,  0,  1},
/* HWIF_PP2_OUT_Y_STRIDE            */ {/*swreg*/368, 16, 16,  1},
/* HWIF_PP2_OUT_C_STRIDE            */ {/*swreg*/368, 16,  0,  1},
/* HWIF_PP2_FLIP_MODE_U             */ {/*swreg*/369,  2, 29,  1},
/* HWIF_PP2_CROP_STARTX_U           */ {/*swreg*/369, 13, 16,  1},
/* HWIF_PP2_ROTATION_MODE_U         */ {/*swreg*/369,  2, 13,  1},
/* HWIF_PP2_CROP_STARTY_U           */ {/*swreg*/369, 13,  0,  1},
/* HWIF_PP2_IN_WIDTH_U              */ {/*swreg*/370, 13, 16,  1},
/* HWIF_PP2_IN_HEIGHT_U             */ {/*swreg*/370, 13,  0,  1},
/* HWIF_PP2_OUT_WIDTH_U             */ {/*swreg*/371, 16, 16,  1},
/* HWIF_PP2_OUT_HEIGHT_U            */ {/*swreg*/371, 16,  0,  1},
/* HWIF_PP2_OUT_LU_BOT_BASE_U_MSB   */ {/*swreg*/372, 32,  0,  1},
/* HWIF_PP2_OUT_LU_BOT_BASE_U_LSB   */ {/*swreg*/373, 32,  0,  1},
/* HWIF_PP2_OUT_CH_BOT_BASE_U_MSB   */ {/*swreg*/374, 32,  0,  1},
/* HWIF_PP2_OUT_CH_BOT_BASE_U_LSB   */ {/*swreg*/375, 32,  0,  1},
/* HWIF_PP3_OUT_TILE_E_U            */ {/*swreg*/376,  1,  3,  1},
/* HWIF_PP3_OUT_MODE                */ {/*swreg*/376,  1,  2,  1},
/* HWIF_PP3_CR_FIRST                */ {/*swreg*/376,  1,  1,  1},
/* HWIF_PP3_OUT_E_U                 */ {/*swreg*/376,  1,  0,  1},
/* HWIF_PP3_OUT_SWAP_U              */ {/*swreg*/377,  4, 20,  1},
/* HWIF_PP3_HOR_SCALE_MODE_U        */ {/*swreg*/378,  2, 25,  1},
/* HWIF_PP3_VER_SCALE_MODE_U        */ {/*swreg*/378,  2, 23,  1},
/* HWIF_PP3_OUT_FORMAT_U            */ {/*swreg*/378,  5, 18,  1},
/* HWIF_PP3_SCALE_HRATIO_U          */ {/*swreg*/378, 18,  0,  1},
/* HWIF_PP3_SCALE_WRATIO_U          */ {/*swreg*/379, 18,  0,  1},
/* HWIF_PP3_WSCALE_INVRA_U          */ {/*swreg*/380, 16, 16,  1},
/* HWIF_PP3_HSCALE_INVRA_U          */ {/*swreg*/380, 16,  0,  1},
/* HWIF_PP3_OUT_LU_BASE_U_MSB       */ {/*swreg*/381, 32,  0,  1},
/* HWIF_PP3_OUT_LU_BASE_U_LSB       */ {/*swreg*/382, 32,  0,  1},
/* HWIF_PP3_OUT_CH_BASE_U_MSB       */ {/*swreg*/383, 32,  0,  1},
/* HWIF_PP3_OUT_CH_BASE_U_LSB       */ {/*swreg*/384, 32,  0,  1},
/* HWIF_PP3_OUT_Y_STRIDE            */ {/*swreg*/385, 16, 16,  1},
/* HWIF_PP3_OUT_C_STRIDE            */ {/*swreg*/385, 16,  0,  1},
/* HWIF_PP3_FLIP_MODE_U             */ {/*swreg*/386,  2, 29,  1},
/* HWIF_PP3_CROP_STARTX_U           */ {/*swreg*/386, 13, 16,  1},
/* HWIF_PP3_ROTATION_MODE_U         */ {/*swreg*/386,  2, 13,  1},
/* HWIF_PP3_CROP_STARTY_U           */ {/*swreg*/386, 13,  0,  1},
/* HWIF_PP3_IN_WIDTH_U              */ {/*swreg*/387, 13, 16,  1},
/* HWIF_PP3_IN_HEIGHT_U             */ {/*swreg*/387, 13,  0,  1},
/* HWIF_PP3_OUT_WIDTH_U             */ {/*swreg*/388, 16, 16,  1},
/* HWIF_PP3_OUT_HEIGHT_U            */ {/*swreg*/388, 16,  0,  1},
/* HWIF_PP3_OUT_LU_BOT_BASE_U_MSB   */ {/*swreg*/389, 32,  0,  1},
/* HWIF_PP3_OUT_LU_BOT_BASE_U_LSB   */ {/*swreg*/390, 32,  0,  1},
/* HWIF_PP3_OUT_CH_BOT_BASE_U_MSB   */ {/*swreg*/391, 32,  0,  1},
/* HWIF_PP3_OUT_CH_BOT_BASE_U_LSB   */ {/*swreg*/392, 32,  0,  1},
/* HWIF_DEC_TIMEOUT_E               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_STRSWAP32_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_STRENDIAN_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_INSWAP32_E              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_OUTSWAP32_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DATA_DISC_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_2CHAN_DIS               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_OUT_TILED_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_LATENCY                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_IN_ENDIAN               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_OUT_ENDIAN              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PRIORITY_MODE               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_ADV_PRE_DIS             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_SCMD_DIS                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_MODE_G1V6               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RLC_MODE_E_G1V6             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PJPEG_E                     */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_AHB_HLOCK_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_STREAM_LEN_EXT              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_VP8_CH_BASE_LSB_E           */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DIR_MV_BASE_LSB2            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_E                     */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_THR                   */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_PICID                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_EVAL_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_FPARMOD_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_Y_OFFSET              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_HIT_SUM               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_INTRA_SUM             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_Y_MV_SUM              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU2_BUF_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU2_THR                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU2_PICID                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_TOP_SUM               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFBU_BOT_SUM               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_CH_BASE_MSB             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CH_BASE_MSB_E               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER0_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER1_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER2_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER3_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER4_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER5_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER6_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER7_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER8_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER9_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER10_CH_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER11_CH_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER12_CH_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER13_CH_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER14_CH_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_REFER15_CH_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DIR_MV_BASE_MSB2            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_BUS_INT                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_RDY_INT                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IRQ                      */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IRQ_DIS                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_PIPELINE_E               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_E                        */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_AXI_RD_ID                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_AXI_WR_ID                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_AHB_HLOCK_E              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_SCMD_DIS                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_A2_ENDSEL             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_A1_SWAP32             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_A1_ENDIAN             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_SWAP32_E              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_DATA_DISC_E              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_CLK_GATE_E               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_ENDIAN                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_ENDIAN               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_SWAP32_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_MAX_BURST                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEINT_E                     */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEINT_THRESHOLD             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEINT_BLEND_E               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEINT_EDGE_DET              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_LU_BASE_LSB           */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_CB_BASE_LSB           */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_CR_BASE_LSB           */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_LU_BASE_LSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_CH_BASE_LSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CONTRAST_THR1               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CONTRAST_OFF2               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CONTRAST_OFF1               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_START_CH              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_CR_FIRST              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_START_CH             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_CR_FIRST             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_COLOR_COEFFA2               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_COLOR_COEFFA1               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CONTRAST_THR2               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_H_EXT                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_COLOR_COEFFD                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_COLOR_COEFFC                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_COLOR_COEFFB                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_W_EXT                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CROP_STARTX                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ROTATION_MODE               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_COLOR_COEFFF                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_COLOR_COEFFE                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CROP_STARTY                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RANGEMAP_COEF_Y             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_HEIGHT                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_WIDTH                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_BOT_YIN_BASE_LSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_BOT_CIN_BASE_LSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RANGEMAP_Y_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RANGEMAP_C_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_YCBCR_RANGE                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RGB_PIX_IN32                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RGB_R_PADD                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RGB_G_PADD                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_SCALE_WRATIO                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_FAST_SCALE_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_STRUCT                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_HOR_SCALE_MODE              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_VER_SCALE_MODE              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RGB_B_PADD                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_SCALE_HRATIO                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_WSCALE_INVRA                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_HSCALE_INVRA                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_R_MASK                      */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_G_MASK                      */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_B_MASK                      */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_FORMAT                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_FORMAT               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_HEIGHT               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_WIDTH                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_TILED_E              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_SWAP16_E             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_CROP8_R_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_CROP8_D_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_FORMAT_ES             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RANGEMAP_COEF_C             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_ABLEND_E              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_STARTY                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_STARTX                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_STARTX_EXT            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_STARTY_EXT            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_STARTX_EXT            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_STARTY_EXT            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_ABLEND_E              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_STARTY                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_STARTX                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_EXT_ORIG_WIDTH              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_E                     */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_ENDY                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_ENDX                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_ENDX_EXT              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK1_ENDY_EXT              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_ENDX_EXT              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_ENDY_EXT              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_E                     */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_ENDY                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_MASK2_ENDX                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RIGHT_CROSS_E               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_LEFT_CROSS_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_UP_CROSS_E                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DOWN_CROSS_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_UP_CROSS                    */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DOWN_CROSS_EXT              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DOWN_CROSS                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DITHER_SELECT_R             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DITHER_SELECT_G             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DITHER_SELECT_B             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_TILED_MODE               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RIGHT_CROSS                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_LEFT_CROSS                  */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_H_EXT                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_W_EXT                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CROP_STARTY_EXT             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_CROP_STARTX_EXT             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_RIGHT_CROSS_EXT             */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_LEFT_CROSS_EXT              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_UP_CROSS_EXT                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DISPLAY_WIDTH               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ABLEND1_BASE_LSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ABLEND2_BASE_LSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ABLEND2_SCANL               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ABLEND1_SCANL               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_LU_BASE_MSB           */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_CB_BASE_MSB           */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_IN_CR_BASE_MSB           */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_LU_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_CH_BASE_MSB          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_BOT_YIN_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_BOT_CIN_BASE_MSB         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ABLEND1_BASE_MSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ABLEND2_BASE_MSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_BUFF_ID                     */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_OUT_SWAP                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_SWAP_64BIT_R                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_SWAP_64BIT_W                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_EXTERNAL_TIMEOUT_OVERRIDE_E */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_EXTERNAL_TIMEOUT_CYCLES     */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_PP_OUT_PIXEL_LINES_U        */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_BUSBUSY                 */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_TAB0_SWAP               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_TAB1_SWAP               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_TAB2_SWAP               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_TAB3_SWAP               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_RSCAN_SWAP              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_COMP_TABLE_SWAP         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_OUT_RS_E                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_OUTPUT_8_BITS               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_OUTPUT_FORMAT               */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_BUSBUSY_CYCLES              */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_CLK_GATE_IDLE_E         */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_RSY_BASE_MSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_RSY_BASE_LSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_RSC_BASE_MSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_RSC_BASE_LSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DS_E                    */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DS_Y                    */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DS_X                    */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DSY_BASE_MSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DSY_BASE_LSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DSC_BASE_MSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_DEC_DSC_BASE_LSB            */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ERROR_ADDR_X                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ERROR_ADDR_Y                */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ERROR_SLICE_HEADER          */ {/*swreg*/  0, 32,  0,  1},
/* HWIF_ERROR_SLICE_DATA            */ {/*swreg*/  0, 32,  0,  1},
