{ /* g1v6-legacy */
  .id = 0x67316000,
  .id_mask = 0xFFFFF000,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 1,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 0,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 0,
  .hevc_support = 0,
  .hevc_main10_support = 0,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 1,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 0,
  .ec_support = 0,
  .dec_stride_support = 0,
  .pp_stride_support = 0,
  .field_dpb_support = 1,
  .double_buffer_support = 1,
  .rfc_support = 0,
  .ring_buffer_support = 0,
  .mrb_prefetch = 0,
  .statistical_level = 0,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 0,
  .tile_decoding_support = 0,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 1,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = G1_NATIVE_PP,
  .jpeg_pp_force_e = 0,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 4,
  .crop_step_rshift = 2,
  .rotation_support = 1,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 0,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* g1v8_1 */
  .id = 0x67317010,
  .id_mask = 0xFFFFFFF0,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 1,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 0,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 0,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 1,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 4,
  .crop_step_rshift = 2,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* g1v8_2 */
  .id = 0x67317020,
  .id_mask = 0xFFFFFFF0,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 1,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 0,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 1,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 4,
  .crop_step_rshift = 2,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* g1v8_3 */
  .id = 0x67327030,
  .id_mask = 0xFFFFFFF0,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 1,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 0,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 0,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 1,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 4,
  .crop_step_rshift = 2,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* g2v4_9 */
  .id = 0x67323090,
  .id_mask = 0xFFFFFFF0,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 0,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 0,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 1,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 1,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 4,
  .crop_step_rshift = 2,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* g2v4 */
  .id = 0x67327300,
  .id_mask = 0xFFFFFF00,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 0,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 0,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 1,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 1,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 4,
  .crop_step_rshift = 2,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v6.1 */
  .id = 0x00006001,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 1,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 1,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 1,
  .has_2nd_h264_pipeline = 1,
  .has_2nd_jpeg_pipeline = 1,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 4,
  .crop_step_rshift = 2,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.0 */
  .id = 0x00001F41,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 0,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 1,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 4,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 0,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.0 */
  .id = 0x00001F42,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 0,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 0,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 0,
  .hevc_main10_support = 0,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 4,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.0 */
  .id = 0x00001F43,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 1,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 0,
  .avs_support = 0,
  .jpeg_esupport = 1,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 0,
  .hevc_support = 0,
  .hevc_main10_support = 0,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 2304,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 0,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 2,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.0 */
  .id = 0x00001F44,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 0,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 0,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 0,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 0,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 2304,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 0,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 2,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.0 */
  .id = 0x00001F45,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 1,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 1,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.1.0 */
  .id = 0x00001F46,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 0,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 0,
  .jpeg_support = 1,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 1,
  .vp9_support = 1,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 1,
  .hevc_main10_support = 0,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 2,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 1,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.1.1 */
  .id = 0x00001F47,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 1,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 2304,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 2,
  .pp_support = 2,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 0,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 1,
  .pp_yuv420_101010_support = 0,
},
{ /* vc8000d_v7.2.0 */
  .id = 0x00001F48,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 3,
  .h264_high10_support = 1,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 1,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 1,
  .avs_support = 0,
  .jpeg_esupport = 1,
  .rv_support = 0,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 0,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 1,
  .max_dec_pic_width = 8192,
  .max_dec_pic_height = 8192,
  .max_pp_out_pic_width = 8192,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 1,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 1,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 1,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 2,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 0,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 0,
  .dither_support = 0,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 1,
},
{ /* h264_high10_debug */
  .id = 0x264DEB,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 3,
  .h264_high10_support = 1,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 0,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 0,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 0,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 0,
  .hevc_main10_support = 0,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 8192,
  .max_dec_pic_height = 4320,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 1,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 1,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 1,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 1,
  .pp_yuv420_101010_support = 0,
},
{ /* full_feature */
  .id = 0x0000FFFE,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 0,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 1,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 1,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 8192,
  .max_dec_pic_height = 8192,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 1,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 1,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 4,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 1,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 1,
  .pp_yuv420_101010_support = 1,
},
{ /* full_feature */
  .id = 0x0000FFFF,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 1,
  .custom_mpeg4_support = 1,
  .h264_support = 3,
  .h264_high10_support = 1,
  .vc1_support = 1,
  .mpeg2_support = 1,
  .jpeg_support = 1,
  .jpeg_prog_support = 1,
  .sorenson_spark_support = 1,
  .vp6_support = 1,
  .vp7_support = 1,
  .vp8_support = 1,
  .vp9_support = 1,
  .avs_support = 1,
  .jpeg_esupport = 1,
  .rv_support = 1,
  .mvc_support = 1,
  .webp_support = 1,
  .avs_plus_support = 1,
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .vp9_profile2_support = 1,
  /* resolution related */
  .max_dec_8k_support = 1,
  .max_dec_pic_width = 8192,
  .max_dec_pic_height = 8192,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 1,
  .ref_buf_support = 0,
  .tiled_mode_support = 1,
  .ref_frame_tiled_only = 1,
  .ec_support = 1,
  .dec_stride_support = 1,
  .pp_stride_support = 1,
  .field_dpb_support = 1,
  .double_buffer_support = 0,
  .rfc_support = 1,
  .ring_buffer_support = 1,
  .mrb_prefetch = 1,
  .statistical_level = 1,
  .strm_len_32bits = 1,
  .pic_size_reg_unified = 1,
  /* decoding flow supported */
  .h264_slice_ec_support = 1,
  .tile_decoding_support = 1,
  .jpeg_slice_decoding_support = 1,
  .low_latency_mode_support = 1,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 4,
  .pp_support = 1,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 1,
  .dscale_support = 1,
  .uscale_support = 1,
  .flexible_scale_support = 1,
  .crop_support = 1,
  .crop_step_unit = 2,
  .crop_step_rshift = 1,
  .rotation_support = 1,
  .dither_support = 1,
  /* output format supported */
  .fmt_p010_support = 1,
  .fmt_customer1_support = 1,
  .pp_pad_e = 1,
  .pp_planar_support = 1,
  .pp_yuv420_101010_support = 1,
},
{ /* none feature */
  .id = 0x00000000,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .h264_support = 0,
  .h264_high10_support = 0,
  .vc1_support = 0,
  .mpeg2_support = 0,
  .jpeg_support = 0,
  .jpeg_prog_support = 0,
  .sorenson_spark_support = 0,
  .vp6_support = 0,
  .vp7_support = 0,
  .vp8_support = 0,
  .vp9_support = 0,
  .avs_support = 0,
  .jpeg_esupport = 0,
  .rv_support = 0,
  .mvc_support = 0,
  .webp_support = 0,
  .avs_plus_support = 0,
  .hevc_support = 0,
  .hevc_main10_support = 0,
  .vp9_profile2_support = 0,
  /* resolution related */
  .max_dec_8k_support = 0,
  .max_dec_pic_width = 4096,
  .max_dec_pic_height = 4096,
  .max_pp_out_pic_width = 4096,
  /* Other features */
  .addr64_support = 0,
  .ref_buf_support = 0,
  .tiled_mode_support = 0,
  .ref_frame_tiled_only = 0,
  .ec_support = 0,
  .dec_stride_support = 0,
  .pp_stride_support = 0,
  .field_dpb_support = 0,
  .double_buffer_support = 0,
  .rfc_support = 0,
  .ring_buffer_support = 0,
  .mrb_prefetch = 0,
  .statistical_level = 0,
  .strm_len_32bits = 0,
  .pic_size_reg_unified = 0,
  /* decoding flow supported */
  .h264_slice_ec_support = 0,
  .tile_decoding_support = 0,
  .jpeg_slice_decoding_support = 0,
  .low_latency_mode_support = 0,
  .has_2nd_pipeline = 0,
  .has_2nd_h264_pipeline = 0,
  .has_2nd_jpeg_pipeline = 0,
  /* registers compatibility */
  .is_legacy_dec_mode = 0,
  /* pp related features */
  .max_ppu_count = 0,
  .pp_support = 0,
  .pp_version = UNFIED_PP,
  .jpeg_pp_force_e = 0,
  .dscale_support = 0,
  .uscale_support = 0,
  .flexible_scale_support = 0,
  .crop_support = 0,
  .crop_step_unit = 0,
  .crop_step_rshift = 0,
  .rotation_support = 0,
  .dither_support = 0,
  /* output format supported */
  .fmt_p010_support = 0,
  .fmt_customer1_support = 0,
  .pp_pad_e = 1,
  .pp_planar_support = 0,
  .pp_yuv420_101010_support = 0,
},
